### ISSUE TITLE
Can't find allure commandline <null>

### ISSUE THREAD

**Issue by papitoio** [jenkinsci/allure-plugin#105]
### Context
- **Jenkins version**: 2.46.1
- **Job type**: Pipeline

- **Allure plugin version**: last
- **Allure commandline version**: 2.5.2

### Problem description

Pipeline code:
allure([includeProperties: false, jdk: '', properties: [], reportBuildPolicy: 'ALWAYS', results: [[path: 'tests/reports']]])

 ERROR:
java.io.IOException: Can't find allure commandline <null>

### Logs & Traces

java.io.IOException: Can't find allure commandline <null>
	at ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation$1.call(AllureCommandlineInstallation.java:46)
	at ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation$1.call(AllureCommandlineInstallation.java:41)
	at hudson.remoting.LocalChannel.call(LocalChannel.java:45)
	at ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation.getExecutable(AllureCommandlineInstallation.java:41)
	at ru.yandex.qatools.allure.jenkins.ReportBuilder.getVersion(ReportBuilder.java:83)
	at ru.yandex.qatools.allure.jenkins.ReportBuilder.build(ReportBuilder.java:42)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:161)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:85)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:78)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:65)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Finished: FAILURE

**Comment by eroshenkoam** [comment]
I'm working on it #101 :)
It's already works in master.

**Comment by fehpapito** [comment]
\o/ thanks

**Comment by eroshenkoam** [comment]
try 2.15, it's should works fine)

**Comment by dayanamcc** [comment]
hello, 
im facing same error but with a Jenkins job type: free-style ,
im using allure-commanline @2.0.1

Done.
ERROR: Step ‘Allure Report’ aborted due to exception: 
java.io.IOException: Can't find allure commandline <null>
	at ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation$2.call(AllureCommandlineInstallation.java:63)
	at ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation$2.call(AllureCommandlineInstallation.java:58)
	at hudson.remoting.LocalChannel.call(LocalChannel.java:45)
	at ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation.getMajorVersion(AllureCommandlineInstallation.java:58)
	at ru.yandex.qatools.allure.jenkins.ReportBuilder.build(ReportBuilder.java:43)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:171)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:94)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1753)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)
Finished: FAILURE



![12](https://user-images.githubusercontent.com/35579/27040304-e22c2a1c-4f90-11e7-968e-83255804bfba.PNG)
![13](https://user-images.githubusercontent.com/35579/27040306-e497e390-4f90-11e7-95d8-5a821169d237.PNG)

**Comment by danalbu** [comment]
**I have the exact same issue on a matrix style job.**

The allure report generates in the children jobs but does not get aggregated to the main job.
Jenkins : 2.46.3
Allure: 1.5.0
Allure Jenkins Plugin: 2.18
Allure cli is installed automatically from central.

**Comment by eroshenkoam** [comment]
@danalbu can you create new ticket for matrix job please

**Comment by danalbu** [comment]
on it :)

**Comment by premaram** [comment]
I still face this issue in allure2.5

**Comment by chandrapola** [comment]
I am using the following Allure Configuration and still facing the issue 

```
[ansible@rcbuild3 ~]$ allure --version
2.4.1
[ansible@rcbuild3 ~]$

```


Facing the following exception

```
GitHub has been notified of this commit’s build result

java.io.IOException: Can't find allure commandline <null>
	at ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation$2.call(AllureCommandlineInstallation.java:63)
	at ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation$2.call(AllureCommandlineInstallation.java:58)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:336)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at ......remote call to ansible-rcbuild3(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1545)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:253)
	at hudson.remoting.Channel.call(Channel.java:830)
	at ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation.getMajorVersion(AllureCommandlineInstallation.java:58)
	at ru.yandex.qatools.allure.jenkins.ReportBuilder.build(ReportBuilder.java:44)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:298)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:223)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:78)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:65)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Finished: FAILURE

```

 Can any one please help in fixing the issue
