### ISSUE TITLE
Unable to use variables in results path

### ISSUE THREAD

**Issue by m3nthal** [jenkinsci/allure-plugin#107]
### Context
- **Jenkins version**: 2.56
- **Job type**: Freestyle

- **Allure plugin version**: 2.15
- **Allure commandline version**: 1.5.2

### Problem description

Using a variable in results path causes build to fail:
- set results path to "allure-results/build-$BUILD_NUMBER"
- the build will fail with NoSuchFileException, but the path indeed contains allure results
- removing variable from results-path resolves the issue

If we take a look in the logs, we'll see that the variable is not substituted with the value.
The main reason to use variables in results path is to isolate results from each other so that report will not be accumulated with each build.

### Logs & Traces

```
15:00:52 ERROR: Step ‘Allure Report’ aborted due to exception: 
15:00:52 java.nio.file.NoSuchFileException: /var/lib/jenkins/workspace/Test/allure-results/build-$BUILD_NUMBER
15:00:52 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
15:00:52 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
15:00:52 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
15:00:52 	at sun.nio.fs.UnixPath.toRealPath(UnixPath.java:837)
15:00:52 	at ru.yandex.qatools.allure.jenkins.callables.AbstractAddInfo.invoke(AbstractAddInfo.java:23)
15:00:52 	at ru.yandex.qatools.allure.jenkins.callables.AbstractAddInfo.invoke(AbstractAddInfo.java:19)
15:00:52 	at hudson.FilePath.act(FilePath.java:997)
15:00:52 	at hudson.FilePath.act(FilePath.java:975)
15:00:52 	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.addTestRunInfo(AllureReportPublisher.java:225)
15:00:52 	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.prepareResults(AllureReportPublisher.java:216)
15:00:52 	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:86)
15:00:52 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
15:00:52 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
15:00:52 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
15:00:52 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
15:00:52 	at hudson.model.Build$BuildExecution.post2(Build.java:186)
15:00:52 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
15:00:52 	at hudson.model.Run.execute(Run.java:1760)
15:00:52 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
15:00:52 	at hudson.model.ResourceController.execute(ResourceController.java:97)
15:00:52 	at hudson.model.Executor.run(Executor.java:405)
15:00:52 Finished: FAILURE
```

**Comment by eroshenkoam** [comment]
I'll fix it in next release, ty
