### ISSUE TITLE
Can't find allure commandline <null>

### ISSUE THREAD

**Issue by padmanabhps** [jenkinsci/allure-plugin#124]
### Context
- **Jenkins version**: 2.46.1
- **Job type**: Not sure how do I know job type

- **Allure plugin version**: 2.17
- **Allure commandline version**: 1.5.2

### Problem description

_Describe your problem in a meaningful way_:
- what were you doing
Jenkins integration of my protractor tests and importing the allure-report generated using the Allure plugin.
- what was expected
Afer using plugin based on following configuration of Allure I should be able to see the report at the end of the tests execution job.
![image](https://cloud.githubusercontent.com/assets/6234464/26708995/212e94e2-476d-11e7-839d-264976c4c0c1.png)

- what occurred finally
I get an exception during the post job step.
ERROR: Step ‘Allure Report’ aborted due to exception: 
java.io.IOException: Can't find allure commandline <null>
	at ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation$2.call(AllureCommandlineInstallation.java:63)
	at ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation$2.call(AllureCommandlineInstallation.java:58)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:336)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at hudson.remoting.Engine$1$1.run(Engine.java:94)
	at java.lang.Thread.run(Unknown Source)
	at ......remote call to JNLP4-connect connection from clm-aus-017610.bmc.com/172.22.105.51:63316(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1545)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:253)
	at hudson.remoting.Channel.call(Channel.java:830)
	at ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation.getMajorVersion(AllureCommandlineInstallation.java:58)
	at ru.yandex.qatools.allure.jenkins.ReportBuilder.build(ReportBuilder.java:43)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:169)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:92)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1753)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)
Finished: FAILURE
### Logs & Traces

_Please include any relevant log that could serve to better understand the source of your issue_

**Comment by eroshenkoam** [comment]
Remove subdirectory `latest`:
![212e94e2-476d-11e7-839d-264976c4c0c1](https://cloud.githubusercontent.com/assets/781455/26713022/fd04b866-4772-11e7-9b91-74e632301f28.png)
