### ISSUE TITLE
NullPointerException during Allure Report step.

### ISSUE THREAD

**Issue by F1ashhimself** [jenkinsci/allure-plugin#125]
## Issue
NullPointerException during Allure Report step.

### Context
- **Jenkins version**: 2.46.3
- **Job type**: Freestyle

- **Allure plugin version**: 2.17
- **Allure commandline version**: 1.5.4

### Logs & Traces
```
13:53:53 ERROR: Build step failed with exception
13:53:53 java.lang.NullPointerException
13:53:53 	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.setAllureProperties(AllureReportPublisher.java:219)
13:53:53 	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:162)
13:53:53 	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:92)
13:53:53 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
13:53:53 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
13:53:53 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
13:53:53 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
13:53:53 	at hudson.model.Build$BuildExecution.post2(Build.java:186)
13:53:53 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
13:53:53 	at hudson.model.Run.execute(Run.java:1753)
13:53:53 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
13:53:53 	at hudson.model.ResourceController.execute(ResourceController.java:98)
13:53:53 	at hudson.model.Executor.run(Executor.java:405)
13:53:53 Build step 'Allure Report' marked build as failure
```

**Comment by F1ashhimself** [comment]
Still the same with plugin 2.19 and CLI 2.2.1.

**Comment by premaram** [comment]
I still face this issue in allure 2.5.0 version. I would appreciate your help. Is there logging to trace
