### ISSUE TITLE
Allure report is not Generated when TMS is specified.

### ISSUE THREAD

**Issue by aosheter** [jenkinsci/allure-plugin#146]
## Issue

Allure report is not Generated when allure.tests.management.pattern key is specified. 

### Context
- **Jenkins version**: 2.60.1
- **Job type**: Freestyle

- **Allure plugin version**: 2.20
- **Allure commandline version**: 2.2.1

### Problem description

We ran tests regularly via Allure, everything worked well. In Allure 1 (a few months ago) allure.tests.management.pattern worked, but we removed it because of some internal implementation issues. After upgrading to Allure 2, I decided to re-add the TMS URL. Now even when all tests pass, Jenkins shows them as failed, because Allure couldn't generate the report. Removing the TMS key solved the issue.

### Logs & Traces

```
[PostBuildScript] - Execution post build scripts.
[JobName] $ /bin/sh -xe /tmp/jenkins3447638176354371552.sh
+ sudo chown -R jenkins:jenkins /srv/jenkins/workspace/
Build step 'Console output (build log) parsing' changed build result to FAILURE
Recording test results
[JobName] $ /srv/jenkins/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/Our-CI/bin/allure generate /srv/jenkins/workspace/JobName/allure_reports -o /srv/jenkins/workspace/JobName/allure-report
/srv/jenkins/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/Our-CI/bin/allure: 1: eval: -classpath: not found
Error: Could not find or load main class generate
ERROR: Build step failed with exception
ru.yandex.qatools.allure.jenkins.exception.AllurePluginException: Can not generate Allure Report, exit code: 1
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:260)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:181)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:735)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:676)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:621)
	at hudson.model.Run.execute(Run.java:1760)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:405)
Build step 'Allure Report' marked build as failure
Started calculate disk usage of build
```

**Comment by vbragin** [comment]
@aosheter According to your stack trace you are using the allure plugin version 2.19.
Try to use the latest version (2.23). It looks like your problem will be solved there.
Please, write about your result here.

**Comment by vbragin** [comment]
@aosheter Does your TMS URL contains '&' symbol?

**Comment by vbragin** [comment]
#162 Looks like the same issue.
