### ISSUE TITLE
[2.22] NPE when trying to generate report

### ISSUE THREAD

**Issue by aiannucci** [jenkinsci/allure-plugin#157]
### Context
- **Jenkins version**: 2.46.2.1
- **Job type**: Maven project

- **Allure plugin version**: 2.22
- **Allure commandline version**: 2.3.1

### Problem description

Allure throws NPE when trying to build a report after the Maven build finishes successfully.
The issue is seen after upgrading to Allure plugin 2.22
allure-results folder has been correctly generated at the expected location.

### Logs & Traces

> 17:06:04 [Mule-4.x-EE] $ /scratch/jenkins/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/allure2/bin/allure generate /scratch/jenkins/workspace/Mule-4.x-EE/target/allure-results -o /scratch/jenkins/workspace/Mule-4.x-EE/allure-report
> 17:06:06 send analytics
> 17:06:06 Exception in thread "main" java.lang.NullPointerException
> 17:06:06 	at java.util.Objects.requireNonNull(Objects.java:203)
> 17:06:06 	at java.util.Optional.<init>(Optional.java:96)
> 17:06:06 	at java.util.Optional.of(Optional.java:108)
> 17:06:06 	at java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:193)
> 17:06:06 	at java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:190)
> 17:06:06 	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
> 17:06:06 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 17:06:06 	at java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:469)
> 17:06:06 	at io.qameta.allure.entity.TestResult.findOneLabel(TestResult.java:100)
> 17:06:06 	at io.qameta.allure.entity.TestResult.findOneLabel(TestResult.java:93)
> 17:06:06 	at io.qameta.allure.packages.PackagesPlugin.createLeaf(PackagesPlugin.java:111)
> 17:06:06 	at io.qameta.allure.tree.AbstractTree.lambda$add$0(AbstractTree.java:33)
> 17:06:06 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
> 17:06:06 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
> 17:06:06 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
> 17:06:06 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
> 17:06:06 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
> 17:06:06 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
> 17:06:06 	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
> 17:06:06 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
> 17:06:06 	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
> 17:06:06 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
> 17:06:06 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> 17:06:06 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> 17:06:06 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
> 17:06:06 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
> 17:06:06 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 17:06:06 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
> 17:06:06 	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
> 17:06:06 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
> 17:06:06 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> 17:06:06 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> 17:06:06 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
> 17:06:06 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
> 17:06:06 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 17:06:06 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
> 17:06:06 	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
> 17:06:06 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
> 17:06:06 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> 17:06:06 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> 17:06:06 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
> 17:06:06 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
> 17:06:06 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 17:06:06 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
> 17:06:06 	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
> 17:06:06 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
> 17:06:06 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> 17:06:06 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> 17:06:06 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
> 17:06:06 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
> 17:06:06 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 17:06:06 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
> 17:06:06 	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
> 17:06:06 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
> 17:06:06 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> 17:06:06 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> 17:06:06 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
> 17:06:06 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
> 17:06:06 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 17:06:06 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
> 17:06:06 	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
> 17:06:06 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
> 17:06:06 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> 17:06:06 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> 17:06:06 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
> 17:06:06 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
> 17:06:06 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 17:06:06 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
> 17:06:06 	at io.qameta.allure.tree.AbstractTree.add(AbstractTree.java:32)
> 17:06:06 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
> 17:06:06 	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1548)
> 17:06:06 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
> 17:06:06 	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
> 17:06:06 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
> 17:06:06 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
> 17:06:06 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> 17:06:06 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> 17:06:06 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
> 17:06:06 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
> 17:06:06 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 17:06:06 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
> 17:06:06 	at io.qameta.allure.packages.PackagesPlugin.getData(PackagesPlugin.java:59)
> 17:06:06 	at io.qameta.allure.packages.PackagesPlugin.aggregate(PackagesPlugin.java:42)
> 17:06:06 	at io.qameta.allure.ReportGenerator.aggregate(ReportGenerator.java:38)
> 17:06:06 	at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:55)
> 17:06:06 	at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:43)
> 17:06:06 	at io.qameta.allure.Commands.generate(Commands.java:88)
> 17:06:06 	at io.qameta.allure.CommandLine.run(CommandLine.java:129)
> 17:06:06 	at java.util.Optional.orElseGet(Optional.java:267)
> 17:06:06 	at io.qameta.allure.CommandLine.main(CommandLine.java:72)
> 17:06:07 ERROR: Build step failed with exception
> 17:06:07 ru.yandex.qatools.allure.jenkins.exception.AllurePluginException: Can not generate Allure Report, exit code: 1
> 17:06:07 	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:265)
> 17:06:07 	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:186)
> 17:06:07 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
> 17:06:07 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
> 17:06:07 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:789)
> 17:06:07 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:730)
> 17:06:07 	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1067)
> 17:06:07 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:675)
> 17:06:07 	at hudson.model.Run.execute(Run.java:1753)
> 17:06:07 	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:544)
> 17:06:07 	at hudson.model.ResourceController.execute(ResourceController.java:98)
> 17:06:07 	at hudson.model.Executor.run(Executor.java:405)
> 17:06:07 Build step 'Allure Report' marked build as failure

**Comment by aiannucci** [comment]
I just saw https://github.com/allure-framework/allure2/issues/522
Does 2.3.2 fix this? If so, please close it
Thanks
