### ISSUE TITLE
Error when creating report in pipeline

### ISSUE THREAD

**Issue by jhulings** [jenkinsci/allure-plugin#159]
## Issue
Getting an error when trying to use the latest version of the plugin in my jenkins pipeline

### Context
- **Jenkins version**: 2.60.3
- **Job type**: Pipeline

- **Allure plugin version**: 2.22

### Problem description

- I have a pipeline set up to build, execute selenium tests, and then report the results of the test using the plugin
- Per the pipeline syntax helper, I am using the follow syntax for my reporting stage: 
```  
stage('Report') {
    allure includeProperties: false, jdk: '', results: [[path: 'allure-results']]
    currentBuild.result = buildresult
  }
```
- I am able to get this working in version 2.16 of the plugin with the following syntax:
```  
stage('Report') {
    allure([config: [[path: 'allure-results']]])
    currentBuild.result = buildresult
  }
```
- I receive the follow error: 

> Cannot find a history information about previous builds.
java.nio.file.NoSuchFileException: /var/lib/jenkins/workspace/Pipeline/allure-results/history/history-trend.json
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
java.nio.file.AccessDeniedException: /var/lib/jenkins/workspace/Pipeline/allure-results/testrun.json
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
	at java.nio.file.Files.newOutputStream(Files.java:216)
	at java.nio.file.Files.newBufferedWriter(Files.java:2860)
	at ru.yandex.qatools.allure.jenkins.callables.AbstractAddInfo.invoke(AbstractAddInfo.java:26)
	at ru.yandex.qatools.allure.jenkins.callables.AbstractAddInfo.invoke(AbstractAddInfo.java:19)
	at hudson.FilePath.act(FilePath.java:998)
	at hudson.FilePath.act(FilePath.java:976)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.addTestRunInfo(AllureReportPublisher.java:349)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.prepareResults(AllureReportPublisher.java:340)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:185)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)_

**Comment by vbragin** [comment]
@jhulings Try to update plugin to latest version and try again.
In case the problem will occur again wright here.

**Comment by jhulings** [comment]
@vbragin I see the same error with the latest version (2.23)

**Comment by eroshenkoam** [comment]
Seems like allure has no write rights to access `allure-results`. 
Can you check this by following script?
```
stage('Report') {
    sh 'ls -al allure-results'
//    allure includeProperties: false, jdk: '', results: [[path: 'allure-results']]
    currentBuild.result = buildresult
  }
```

**Comment by jhulings** [comment]
@eroshenkoam Output of ls -al allure-results: 

+ ls -al allure-results
total 60
drwxr-xr-x 2 root    root     4096 Oct 10 12:29 .
drwxr-xr-x 7 jenkins jenkins  4096 Oct 10 12:29 ..
-rw-r--r-- 1 root    root     3854 Oct 10 12:29 15c0d232-8411-4e8a-9869-8699aec6848a-testsuite.xml
-rw-r--r-- 1 root    root     2986 Oct 10 12:29 91601f48-1d34-4997-8616-f36e1dc850c8-attachment.txt
-rw-r--r-- 1 root    root    42804 Oct 10 12:29 f07d998c-835d-46cb-9fc5-00cec32304aa-attachment.png

**Comment by eroshenkoam** [comment]
Seems like you run your tests as `root` user (or in `sudo` mode). 
And allure can't write any files because it runs as `jenkins` users. 

You can fix it by following script: 
```
stage('Report') {
    sh 'chmod -R o+xw allure-results'
    allure results: [[path: 'allure-results']]
    currentBuild.result = buildresult
}
```

**Comment by jhulings** [comment]
Thank you. I understand the issue now. The chmod command does not work because of my configuration, but I am able to fix it by making sure my tests are run by the jenkins user so that the allure-results folder is created by that user. Thank you for your help!

**Comment by cardinalX** [comment]
I fix it by `sh "mkdir -p ./results/allure-results"` before running docker with tests 
`sh """
docker run --name ui_tests -v "\$(pwd)"/results/allure-results:/allure-results """
`

**Comment by abhisheksh-nd** [comment]
#!/bin/bash

# Create the directories for Allure results and pytest results
mkdir -p ./reports/allure-results
