### ISSUE TITLE
Error during report generation

### ISSUE THREAD

**Issue by polyanskyiow** [jenkinsci/allure-plugin#16]
The following error occurs while generating a report using the Allure Jenkins Plugin (plugin version 2.6)

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running my.company.SimpleTest
Configuring TestNG with: TestNG652Configurator
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.673 sec - in my.company.SimpleTest

Results :

Tests run: 4, Failures: 0, Errors: 0, Skipped: 0

[JENKINS] Recording test results
log4j:WARN No appenders could be found for logger (org.apache.commons.beanutils.converters.BooleanConverter).
log4j:WARN Please initialize the log4j system properly.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.818 s
[INFO] Finished at: 2015-07-31T16:47:01+03:00
[INFO] Final Memory: 25M/343M
[INFO] ------------------------------------------------------------------------
Ожидаю пока Jenkins закончит сбор данных
[JENKINS] Archiving C:\Jenkins\workspace\allure\pom.xml to ru.yandex.qatools.allure/allure-testng-example/1.0-SNAPSHOT/allure-testng-example-1.0-SNAPSHOT.pom
channel stopped
Allure Report Generation: started
Allure Report Generation: find directories by mask [**/allure-results]
Allure Report Generation: found allure result directories [C:\Jenkins\workspace\allure\target\allure-results]
Allure Report Generation: copy founded directories in directory [C:\Jenkins\workspace\allure\allure8063768305174617023.tmp\results]
Allure Report Generation: generate report from directory [C:\Jenkins\workspace\allure\allure8063768305174617023.tmp]
Allure Report Generation: proxy settings [active:'false', host:'null', port:'0', username:'null', password: '']
ERROR: Publisher 'Allure Report Generation' aborted due to exception: 
java.io.IOException: ru.yandex.qatools.allure.report.AllureReportBuilderException: java.lang.ClassNotFoundException: ru.yandex.qatools.allure.data.AllureReportGenerator
    at ru.yandex.qatools.allure.jenkins.utils.ReportGenerator.invoke(ReportGenerator.java:50)
    at ru.yandex.qatools.allure.jenkins.utils.ReportGenerator.invoke(ReportGenerator.java:25)
    at hudson.FilePath.act(FilePath.java:989)
    at hudson.FilePath.act(FilePath.java:967)
    at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:267)
    at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:146)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:776)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
    at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1037)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
    at hudson.model.Run.execute(Run.java:1763)
    at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:529)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:381)
Caused by: ru.yandex.qatools.allure.report.AllureReportBuilderException: java.lang.ClassNotFoundException: ru.yandex.qatools.allure.data.AllureReportGenerator
    at ru.yandex.qatools.allure.report.AllureReportBuilder.processResults(AllureReportBuilder.java:133)
    at ru.yandex.qatools.allure.jenkins.utils.ReportGenerator.invoke(ReportGenerator.java:47)
    ... 14 more
Caused by: java.lang.ClassNotFoundException: ru.yandex.qatools.allure.data.AllureReportGenerator
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at ru.yandex.qatools.allure.report.AllureReportBuilder.processResults(AllureReportBuilder.java:129)
    ... 15 more
Finished: FAILURE

Java  jdk1.7.0_55
Maven 3.3.3

Jenkins works under proxy.

**Comment by Varomir** [comment]
Hi I have the same issue
---------------------------------------------
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.860s
[INFO] Finished at: Thu Aug 20 18:37:33 EEST 2015
[INFO] Final Memory: 18M/185M
[INFO] ------------------------------------------------------------------------
Allure Report Generation: started
Allure Report Generation: find directories by mask [**/allure-results]
Allure Report Generation: found allure result directories [/var/lib/jenkins/jobs/OpenAPI-smoke/workspace/target/allure-results]
Allure Report Generation: copy founded directories in directory [/var/lib/jenkins/jobs/OpenAPI-smoke/workspace/allure7647904248904999211.tmp/results]
Allure Report Generation: generate report from directory [/var/lib/jenkins/jobs/OpenAPI-smoke/workspace/allure7647904248904999211.tmp]
Allure Report Generation: proxy settings [active:'false', host:'null', port:'0', username:'null', password: '']

ERROR: Publisher ru.yandex.qatools.allure.jenkins.AllureReportPublisher aborted due to exception
java.io.IOException: ru.yandex.qatools.allure.report.AllureReportBuilderException: java.lang.reflect.InvocationTargetException
	at ru.yandex.qatools.allure.jenkins.utils.ReportGenerator.invoke(ReportGenerator.java:50)
	at ru.yandex.qatools.allure.jenkins.utils.ReportGenerator.invoke(ReportGenerator.java:25)
	at hudson.FilePath.act(FilePath.java:989)
	at hudson.FilePath.act(FilePath.java:967)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:267)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:146)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:721)
	at hudson.model.Build$BuildExecution.post2(Build.java:183)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
	at hudson.model.Run.execute(Run.java:1743)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
Caused by: ru.yandex.qatools.allure.report.AllureReportBuilderException: java.lang.reflect.InvocationTargetException
	at ru.yandex.qatools.allure.report.AllureReportBuilder.processResults(AllureReportBuilder.java:133)
	at ru.yandex.qatools.allure.jenkins.utils.ReportGenerator.invoke(ReportGenerator.java:47)
	... 14 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at ru.yandex.qatools.allure.report.AllureReportBuilder.processResults(AllureReportBuilder.java:131)
	... 15 more
Caused by: java.lang.OutOfMemoryError: PermGen space
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at com.fasterxml.jackson.databind.ser.BasicSerializerFactory.<clinit>(BasicSerializerFactory.java:80)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:455)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:366)
	at ru.yandex.qatools.allure.data.utils.AllureReportUtils.createMapperWithJaxbAnnotationInspector(AllureReportUtils.java:98)
	at ru.yandex.qatools.allure.data.utils.AllureReportUtils.serialize(AllureReportUtils.java:81)
	at ru.yandex.qatools.allure.data.utils.AllureReportUtils$serialize$0.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:53)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:191)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:211)
	at ru.yandex.qatools.allure.data.io.ReportWriter.serializeToData(ReportWriter.groovy:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:151)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at ru.yandex.qatools.allure.data.io.ReportWriter.write(ReportWriter.groovy:67)
	at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:67)

Recording test results
ERROR: Publisher hudson.tasks.junit.JUnitResultArchiver aborted due to exception
hudson.AbortException: No test report files were found. Configuration error?
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:116)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:92)
	at hudson.FilePath.act(FilePath.java:989)
	at hudson.FilePath.act(FilePath.java:967)
	at hudson.tasks.junit.JUnitParser.parseResult(JUnitParser.java:89)
	at hudson.tasks.junit.JUnitResultArchiver.parse(JUnitResultArchiver.java:121)
	at hudson.tasks.junit.JUnitResultArchiver.perform(JUnitResultArchiver.java:138)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:74)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:721)
	at hudson.model.Build$BuildExecution.post2(Build.java:183)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
	at hudson.model.Run.execute(Run.java:1743)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
Sending e-mails to: Vadym.Feshchenko@playtech.com Igor.Khovrichev@playtech.com
Finished: FAILURE

root@ua-portal-automation-5:~# ps aux | grep java
jenkins  24969  0.0  0.0   6180   364 ?        S    10:31   0:00 /usr/bin/daemon --name=jenkins --inherit --env=JENKINS_HOME=/var/lib/jenkins --output=/var/log/jenkins/jenkins.log --pidfile=/var/run/jenkins/jenkins.pid -- /usr/bin/java -Djava.awt.headless=true -jar /usr/share/jenkins/jenkins.war --webroot=/var/cache/jenkins/war --httpPort=8080 --ajp13Port=-1
jenkins  24971  1.5  6.8 1310904 569700 ?      Sl   10:31   1:17 /usr/bin/java -Djava.awt.headless=true -jar /usr/share/jenkins/jenkins.war --webroot=/var/cache/jenkins/war --httpPort=8080 --ajp13Port=-1


---------------------------------------------------------
root@ua-portal-automation-5:~# java -version
java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) Server VM (build 24.51-b03, mixed mode)

---------------------------------------------------------
root@ua-portal-automation-5:~# mvn -version
Apache Maven 3.2.1 (ea8b2b07643dbb1b84b6d16e1f08391b666bc1e9; 2014-02-14T19:37:52+02:00)
Maven home: /usr/share/maven3
Java version: 1.7.0_51, vendor: Oracle Corporation
Java home: /opt/java/jdk1.7.0_51/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-44-generic", arch: "i386", family: "unix"

---------------------------------------------------------
root@ua-portal-automation-5:~# df
Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/sda1      112480984 52603984  54140268  50% /
none                   4        0         4   0% /sys/fs/cgroup
udev             4132384       12   4132372   1% /dev
tmpfs             828400      976    827424   1% /run
none                5120        0      5120   0% /run/lock
none             4141984      396   4141588   1% /run/shm
none              102400        8    102392   1% /run/user

**Comment by breinjhel** [comment]
Same here. Im getting these errors and I already added proxy host and port on my jenkins.

And also Im running the job in a slave machine.

**Comment by polyanskyiow** [comment]
Thx for fix)
It works fine now.

**Comment by omkartelang** [comment]
Hello,

Can you please help me as I am getting following error and when I checked allure results in workspace, then it did not generated in it however it was generated in target folder in project.

[TestAutomaitonMaven] $ C:\Users\telango\.jenkins\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\AllureReport\bin\allure.bat generate -c -o C:\Users\telango\.jenkins\workspace\TestAutomaitonMaven\allure-report
allure-results does not exists
Report successfully generated to C:\Users\telango\.jenkins\workspace\TestAutomaitonMaven\allure-report
Allure report was successfully generated.
Creating artifact for the build.
Artifact was added to the build.
