### ISSUE TITLE
NPE while generating report

### ISSUE THREAD

**Issue by amangrover1** [jenkinsci/allure-plugin#161]
## Issue
NPE while generating report

### Context
- **Jenkins version**: 2.7.8
- **Job type**: Multi Configuration.

- **Allure plugin version**: 2.23
- **Allure commandline version**: 2.3.5

### Problem description

_Describe your problem in a meaningful way_:
- Trying to generate allure report
- what was expected
- what occurred finally

### Logs & Traces
Build step 'Execute Windows batch command' marked build as failure
ERROR: Build step failed with exception
java.lang.NullPointerException
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:181)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:736)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:682)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:627)
	at hudson.model.Run.execute(Run.java:1749)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:419)
Build step 'Allure Report' marked build as failure
Finished: FAILURE
_Please include any relevant log that could serve to better understand the source of your issue_

**Comment by vbragin** [comment]
@amangrover1 Please make sure the allure "Results" property exists in the job's configuration.
The report always generate based on files in this folder.
