### ISSUE TITLE
NullPointerExceptpo

### ISSUE THREAD

**Issue by sepa-joe** [jenkinsci/allure-plugin#183]
Getting a NullPointerException when building the allure reports from Jenkins - note that this was working before I upgraded to Java 8 - also, the report is being generated, but something is reporting a fail.  The output I am seeing is shown below.

Jenkins version: 2.93
Job type: Freestyle
Allure plugin version: 2.25
- **Allure commandline version**: X.Y.Z

Report has been working - I decided to upgrade to java 8 and update the allure plugin.  The report seems to be getting produced, so can't see anything which is immediately wrong - looking for any hints?

Logs & Traces

`[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:50 min
[INFO] Finished at: 2017-12-06T13:33:44+00:00
[INFO] Final Memory: 22M/203M
[INFO] ------------------------------------------------------------------------
[Table_Counts] $ C:\Allure\1.4.24.RC2\bin\allure.bat generate "C:\Users\Joseph.Adams\.jenkins\workspace\Database_Tests\Table_Counts\target\allure-results" -o "C:\Users\Joseph.Adams\.jenkins\workspace\Database_Tests\Table_Counts\allure-report"
Report successfully generated to the directory <C:\Users\Joseph.Adams\.jenkins\workspace\Database_Tests\Table_Counts\allure-report>. Use `allure report open` command to show the report.
Allure report was successfully generated.
Creating artifact for the build.
Artifact was added to the build.
ERROR: Build step failed with exception
java.lang.NullPointerException
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:308)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:223)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1752)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Allure Report' marked build as failure`

**Comment by vbragin** [comment]
The same issue #172
