### ISSUE TITLE
ERROR: Step ‘Allure Report’ aborted due to exception

### ISSUE THREAD

**Issue by igijedi** [jenkinsci/allure-plugin#206]
### Context
- **Jenkins version**: 2.9
- **Job type**: Freestyle

- **Allure plugin version**: 2.26
- **Allure commandline version**: 2.6.0

### Logs & Traces

ERROR: Step ‘Allure Report’ aborted due to exception: 
java.io.IOException: remote file operation failed: /Users/Shared/Jenkins/Home/workspace/SHDR_GQE_Web/Stage/Smoke_Test_Stage/reports at hudson.remoting.Channel@229480ec:Mac Pro - Tron: java.io.IOException: Remote call on Mac Pro - Tron failed
	at hudson.FilePath.act(FilePath.java:1014)
	at hudson.FilePath.act(FilePath.java:996)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.addTestRunInfo(AllureReportPublisher.java:381)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.prepareResults(AllureReportPublisher.java:372)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:217)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1745)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Caused by: java.io.IOException: Remote call on Mac Pro - Tron failed
	at hudson.remoting.Channel.call(Channel.java:789)
	at hudson.FilePath.act(FilePath.java:1007)
	... 14 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.sf.json.JsonConfig
	at net.sf.json.JSONObject.fromObject(JSONObject.java:132)
	at ru.yandex.qatools.allure.jenkins.callables.AbstractAddInfo.invoke(AbstractAddInfo.java:27)
	at ru.yandex.qatools.allure.jenkins.callables.AbstractAddInfo.invoke(AbstractAddInfo.java:19)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2772)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:332)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
	at ......remote call to Mac Pro - Tron(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:253)
	at hudson.remoting.Channel.call(Channel.java:781)
	... 15 more

**Comment by wsoula** [comment]
I ran into this same issue after upgrading our slaves to java 8.  I was able to fix it by putting the json-lib jar in JAVA_HOME/lib.  I got the jar from http://www.java2s.com/Code/Jar/j/Downloadjsonlib24jdk15jar.htm

**Comment by baev** [comment]
closed as stale
