### ISSUE TITLE
allure executable should be resolved from PATH or ALLURE_HOME

### ISSUE THREAD

**Issue by taraspos** [jenkinsci/allure-plugin#218]
### Context
- **Jenkins version**: 2.140
- **Job type**: Pipeline

- **Allure plugin version**: 2.27
- **Allure commandline version**: 2.7.0

### Problem description

Plugin doesn't resolve `allure` executable from PATH or ALLURE_HOME variable and works only if Tool Installation is set.

### Logs & Traces

```
[Pipeline] step
Error when executing always post condition:
java.io.IOException: Can't find allure commandline <null>
	at ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation$2.call(AllureCommandlineInstallation.java:63)
	at ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation$2.call(AllureCommandlineInstallation.java:58)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
	at java.lang.Thread.run(Thread.java:748)
```

### Related issues

- #205 

- #105 

- #207 

### Proposed fix:
Resolve allure binary from `PATH` [here](https://github.com/jenkinsci/allure-plugin/blob/ff407120d9ee232579fa7985b4fd337e48c942e8/src/main/java/ru/yandex/qatools/allure/jenkins/tools/AllureCommandlineInstallation.java#L95)
and resolve `ALLURE_HOME` variable as a path to Allure installation [here](https://github.com/jenkinsci/allure-plugin/blob/ff407120d9ee232579fa7985b4fd337e48c942e8/src/main/java/ru/yandex/qatools/allure/jenkins/tools/AllureCommandlineInstallation.java#L72)

**Comment by arcones** [comment]
We found a workaround for this placing allure CLI directly in the root of the docker image where we run the pipelines (our agent) and creating a symlink from there to `/bin`.

Once downloaded & unpacked the allure-commandline-X.Y.Z.zip  doing something like this:

```
    mv allure-commandline-X.Y.Z /allure-cli && \
    ln -s /allure-cli/bin/allure /bin/allure
```

where X.Y.Z is the version of allure CLI
