### ISSUE TITLE
Cannot execute testNG+Gradle+Selenium+Allure2+Jenkins

### ISSUE THREAD

**Issue by dimencionrider** [jenkinsci/allure-plugin#222]
## Issue
I cannot execute my framework on Jenkins, because Allure cannot download the plugin.
I'm using testNG(xml test suites)+Gradle+Selenium+Allure2+Jenkins

### Context
- **Jenkins version**: 2.149
- **Job type**: AQA/Dev ops activities

- **Allure plugin version**: 2.5

### Problem description

_I cannot execute my build.gradle via Allure plugin at CI level on server machine where is jenkins located_:
Looks like gradle cannot download the plugin from the central repository and that's why it might fail.
1) Is there any alternative way to use the plugin for Allure together with Jenkins and use local repository instead?

2) Even when I specify the correct path into "target" folder for allure-results/reports it is generating the files into "build/target/..." folder by default. Problem with testNG support?

Here is my build.gradle file:

```buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "io.qameta.allure:allure-gradle:2.5"
    }
}

plugins {
    id "io.qameta.allure" version "2.5"
    id "com.gradle.build-scan" version "1.13.4"
}


group "rocket-test"
version "1.0-SNAPSHOT"

apply plugin: 'idea'
apply plugin: 'java'
apply plugin: 'maven'
apply plugin: 'org.gradle.java'
apply plugin: 'application'

allure {
    version = "2.4.1"
    autoconfigure = true
    aspectjweaver = true
    resultsDir = file("target/allure-results")
    reportDir = file("target/allure-reports")

    downloadLink = "https://dl.bintray.com/qameta/generic/io/qameta/allure/allure/2.4.1/allure-2.4.1.zip"
}

repositories {
    mavenCentral()
}

sourceCompatibility = 1.8

sourceSets { main { java { include "src/test/java/core/tests/**/.java" } } }

def lightTestSuite = project.hasProperty("lightTestSuite")
def smokeTestSuite = project.hasProperty("smokeTestSuite")
def regressionTestSuite = project.hasProperty("regressionTestSuite")


test {
    useTestNG() {
        dependsOn cleanTest
        systemProperties System.getProperties()
        if (lightTestSuite) {
            suites "src/test/resources/light_suite.xml"
        }

        if (smokeTestSuite) {
            suites "src/test/resources/smoke_suite.xml"
        }

        if (regressionTestSuite) {
            suites "src/test/resources/regression_suite.xml"
        }
    }
}

configurations {
    agent
}

repositories {
    maven {
        url "https://plugins.gradle.org/m2/"
    }

    dependencies {
        testCompile group: 'org.testng', name: 'testng', version: '6.8.1'
        compile group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '3.14.0'
        compile group: 'ru.yandex.qatools.allure', name: 'allure-testng-adaptor', version: '1.5.4'
        compile group: 'io.qameta.allure', name: 'allure-gradle', version: '2.5'
        agent 'org.aspectj:aspectjweaver:1.8.10'
    }
}

test.doFirst {
    jvmArgs "-javaagent:${configurations.agent.singleFile}"
}```


### Logs & Traces
Jenkins logs:

```Starting a Gradle Daemon (subsequent builds will be faster)
FAILURE: Build failed with an exception.

* Where:
Build file '/var/lib/jenkins/workspace/automated_gui_tests/build.gradle' line: 13

* What went wrong:
Plugin [id: 'io.qameta.allure', version: '2.5'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'io.qameta.allure:io.qameta.allure.gradle.plugin:2.5')
  Searched in the following repositories:
    maven(file:/var/lib/jenkins/workspace/automated_gui_tests/maven-repo)
    Gradle Central Plugin Repository
    ivy(file:/var/lib/jenkins/workspace/automated_gui_tests/ivy-repo)

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'io.qameta.allure', version: '2.5'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'io.qameta.allure:io.qameta.allure.gradle.plugin:2.5')
  Searched in the following repositories:
    maven(file:/var/lib/jenkins/workspace/automated_gui_tests/maven-repo)
    Gradle Central Plugin Repository
    ivy(file:/var/lib/jenkins/workspace/automated_gui_tests/ivy-repo)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.resolveToFoundResult(DefaultPluginRequestApplicator.java:262)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.access$100(DefaultPluginRequestApplicator.java:63)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator$1.transform(DefaultPluginRequestApplicator.java:91)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator$1.transform(DefaultPluginRequestApplicator.java:88)
	at org.gradle.util.CollectionUtils.collect(CollectionUtils.java:204)```

P.S. Everything works well on my local env

**Comment by dimencionrider** [comment]
Another case(script):

[automated_gui_tests] $ /var/lib/jenkins/workspace/automated_gui_tests/gradlew getHomeDir
Starting a Gradle Daemon (subsequent builds will be faster)
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'automated_gui_tests'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve io.qameta.allure:allure-gradle:2.5.
     Required by:
         project :
      > Could not resolve io.qameta.allure:allure-gradle:2.5.
         > Could not get resource 'https://plugins.gradle.org/m2/io/qameta/allure/allure-gradle/2.5/allure-gradle-2.5.pom'.
            > Could not GET 'https://plugins.gradle.org/m2/io/qameta/allure/allure-gradle/2.5/allure-gradle-2.5.pom'.
               > Connect to plugins.gradle.org:443 [plugins.gradle.org/104.16.171.166, plugins.gradle.org/104.16.172.166, plugins.gradle.org/104.16.173.166, plugins.gradle.org/104.16.175.166, plugins.gradle.org/104.16.174.166, plugins.gradle.org/2606:4700:0:0:0:0:6810:aba6, plugins.gradle.org/2606:4700:0:0:0:0:6810:ada6, plugins.gradle.org/2606:4700:0:0:0:0:6810:aca6, plugins.gradle.org/2606:4700:0:0:0:0:6810:afa6, plugins.gradle.org/2606:4700:0:0:0:0:6810:aea6] failed: Network is unreachable

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 34s

**Comment by dimencionrider** [comment]
It is working now!
The problem was solved by downloading local repo and all libraries on the server side.
Thanks! :)
