### ISSUE TITLE
Slow archiving artifacts

### ISSUE THREAD

**Issue by baev** [jenkinsci/allure-plugin#228]
## Issue

There are few problems with archiving report artifacts. Sometimes it takes too long, sometimes it causes OOM on agents.

## Related issues and questions

https://stackoverflow.com/questions/46466590/how-to-totally-avoid-creating-jenkins-artifacts-after-each-build

https://stackoverflow.com/questions/23505098/jenkins-slaves-go-offline-or-hang-when-archiving-artifacts

https://github.com/allure-framework/allure2/issues/877

## Context

| Generate report using | allure-commandline 2.6.0 |
|---|----|
|Allure Jenkins Plugin | 2.27.0 |
| Jenkins | 2.156 |

**Comment by felipecrs** [comment]
Is there any known workaround for the moment? If I increase the memory of my Jenkins agents (not the Jenkins master), the issue is gone, but I wonder if there is another option. This issue started to happen when we increased the number of tests.




```log
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
  at java.base/java.util.HashMap.newNode(HashMap.java:1815)
  at java.base/java.util.HashMap.putVal(HashMap.java:627)
  at java.base/java.util.HashMap.putMapEntries(HashMap.java:511)
  at java.base/java.util.HashMap.putAll(HashMap.java:781)
  at io.qameta.allure.history.HistoryPlugin.lambda$getData$1(HistoryPlugin.java:119)
  at io.qameta.allure.history.HistoryPlugin$$Lambda$205/0x0000000800242440.apply(Unknown Source)
  at java.base/java.util.stream.ReduceOps$1ReducingSink.accept(ReduceOps.java:80)
  at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
  at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
  at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
  at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
  at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
  at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:553)
  at io.qameta.allure.history.HistoryPlugin.getData(HistoryPlugin.java:118)
  at io.qameta.allure.history.HistoryPlugin.aggregate(HistoryPlugin.java:88)
  at io.qameta.allure.ReportGenerator.aggregate(ReportGenerator.java:53)
  at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:70)
  at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:58)
  at io.qameta.allure.Commands.generate(Commands.java:104)
  at io.qameta.allure.CommandLine.run(CommandLine.java:152)
  at io.qameta.allure.CommandLine$$Lambda$9/0x00000008000af840.get(Unknown Source)
  at java.base/java.util.Optional.orElseGet(Optional.java:369)
  at io.qameta.allure.CommandLine.main(CommandLine.java:88)

Can not generate Allure Report, exit code: 1
```

Tested with allure-commandline 2.17.3.

**Comment by yuqingqing** [comment]
I had the same problem, creating artifacts was too slow, taking more than 3 hours, my allure-report directory is 5.7G
