### ISSUE TITLE
allure bash script being run on windows instead of allure.bat, fails finding non-existent cygwin install

### ISSUE THREAD

**Issue by snowymike** [jenkinsci/allure-plugin#229]
## Issue

The allure bash script, instead of allure.bat, is being run on the Windows slave, which fails due to the lack of a Cygwin installation.

### Context
- **Jenkins version**: 2.153
- **Job type**: Freestyle

- **Allure plugin version**: 2.27.0
- **Allure commandline version**: 2.9.0

### Problem description

I'm trying to capture an Allure report as part of a Jenkins job.  Jenkins server and slave are both Windows.  Windows slave does not have Cygwin installed.

I've configured this post-build action

![image](https://user-images.githubusercontent.com/7119031/52064747-3e505780-2543-11e9-8ab6-696421313daa.png)

And i've configured the Allure Commandline as follows

![image](https://user-images.githubusercontent.com/7119031/52064807-57f19f00-2543-11e9-8b9e-ddd4d9e1e631.png)

The install of the command line works successfully on the slave

![image](https://user-images.githubusercontent.com/7119031/52064865-7192e680-2543-11e9-8add-403939f5bfa5.png)

But when the post-build action runs, it fails.

Judging by the output I assumed it was trying to run the bash script.  I've confirmed that by renaming the bash script on the slave, which results in a different error.

I've never needed Cygwin on this Windows slave before, and I didn't see anything in the documentation that suggested this plugin requires Cygwin on Windows slaves.  I can run allure.bat find manually on the slave system.  I can also run the allure bash script fine through Git Bash on the slave.

### Logs & Traces

Here's the output from the Jenkins job where it successfully unpacks the allure-commandline but then fails to run allure.
```
Unpacking https://repo.jenkins-ci.org/maven-repo1/io/qameta/allure/allure-commandline/2.9.0/allure-commandline-2.9.0.zip to C:\jenkins_slave\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\Allure_2.9.0 on csaqa-vm40
ERROR: Step ‘Allure Report’ aborted due to exception: 
hudson.util.jna.JnaException: Win32 error: 2 - null
	at hudson.util.jna.RegistryKey.check(RegistryKey.java:124)
	at hudson.util.jna.RegistryKey.open(RegistryKey.java:223)
	at hudson.util.jna.RegistryKey.openReadonly(RegistryKey.java:218)
	at hudson.plugins.cygpath.CygpathLauncherDecorator$GetCygpathTask.getCygwinRoot(CygpathLauncherDecorator.java:127)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 16.78.68.149/16.78.68.149:53143
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:955)
		at hudson.plugins.cygpath.CygpathLauncherDecorator$1.getCygpathExe(CygpathLauncherDecorator.java:104)
		at hudson.plugins.cygpath.CygpathLauncherDecorator$1.cygpath(CygpathLauncherDecorator.java:86)
		at hudson.plugins.cygpath.CygpathLauncherDecorator$1.launch(CygpathLauncherDecorator.java:65)
		at hudson.Launcher$ProcStarter.start(Launcher.java:455)
		at hudson.Launcher$ProcStarter.join(Launcher.java:466)
		at ru.yandex.qatools.allure.jenkins.ReportBuilder.build(ReportBuilder.java:48)
		at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:294)
		at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:218)
		at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
		at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
		at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
		at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
		at hudson.model.Build$BuildExecution.post2(Build.java:186)
		at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
		at hudson.model.Run.execute(Run.java:1835)
		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
		at hudson.model.ResourceController.execute(ResourceController.java:97)
		at hudson.model.Executor.run(Executor.java:429)
Caused: hudson.util.IOException2: Failed to locate Cygwin installation. Is Cygwin installed?
	at hudson.plugins.cygpath.CygpathLauncherDecorator$GetCygpathTask.getCygwinRoot(CygpathLauncherDecorator.java:138)
	at hudson.plugins.cygpath.CygpathLauncherDecorator$GetCygpathTask.call(CygpathLauncherDecorator.java:142)
	at hudson.plugins.cygpath.CygpathLauncherDecorator$GetCygpathTask.call(CygpathLauncherDecorator.java:112)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by snowymike** [comment]
Jenkins 2.179, Allure Commandline 2.12.1, and Allure Jenkins Plugin 2.28.1 has the same issue.  the console output is a bit different, but again appears to be attempting to use a non-existent Cygwin install on a Windows slave

```
Unpacking https://repo.jenkins-ci.org/maven-repo1/io/qameta/allure/allure-commandline/2.12.1/allure-commandline-2.12.1.zip to C:\jenkins_slave\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\Allure_2.12.1 on csaqa-vm40
ERROR: Step ‘Allure Report’ aborted due to exception: 
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 16.78.68.149/16.78.68.149:57664
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1743)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:957)
		at hudson.plugins.cygpath.CygpathLauncherDecorator$1.getCygpathExe(CygpathLauncherDecorator.java:104)
		at hudson.plugins.cygpath.CygpathLauncherDecorator$1.cygpath(CygpathLauncherDecorator.java:86)
		at hudson.plugins.cygpath.CygpathLauncherDecorator$1.launch(CygpathLauncherDecorator.java:65)
		at hudson.Launcher$ProcStarter.start(Launcher.java:455)
		at hudson.Launcher$ProcStarter.join(Launcher.java:466)
		at ru.yandex.qatools.allure.jenkins.ReportBuilder.build(ReportBuilder.java:56)
		at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:312)
		at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:231)
		at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:79)
		at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
		at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
		at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
		at hudson.model.Build$BuildExecution.post2(Build.java:186)
		at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
		at hudson.model.Run.execute(Run.java:1843)
		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
		at hudson.model.ResourceController.execute(ResourceController.java:97)
		at hudson.model.Executor.run(Executor.java:429)
java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Pointer
	at com.sun.jna.PointerType.<init>(PointerType.java:36)
	at com.sun.jna.ptr.ByReference.<init>(ByReference.java:41)
	at com.sun.jna.ptr.IntByReference.<init>(IntByReference.java:33)
	at com.sun.jna.ptr.IntByReference.<init>(IntByReference.java:29)
	at hudson.util.jna.RegistryKey.open(RegistryKey.java:215)
	at hudson.util.jna.RegistryKey.openReadonly(RegistryKey.java:211)
	at hudson.plugins.cygpath.CygpathLauncherDecorator$GetCygpathTask.getCygwinRoot(CygpathLauncherDecorator.java:117)
	at hudson.plugins.cygpath.CygpathLauncherDecorator$GetCygpathTask.call(CygpathLauncherDecorator.java:142)
	at hudson.plugins.cygpath.CygpathLauncherDecorator$GetCygpathTask.call(CygpathLauncherDecorator.java:112)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
	at java.lang.Thread.run(Unknown Source)
Caused: java.io.IOException: Remote call on JNLP4-connect connection from 16.78.68.149/16.78.68.149:57664 failed
	at hudson.remoting.Channel.call(Channel.java:963)
	at hudson.plugins.cygpath.CygpathLauncherDecorator$1.getCygpathExe(CygpathLauncherDecorator.java:104)
	at hudson.plugins.cygpath.CygpathLauncherDecorator$1.cygpath(CygpathLauncherDecorator.java:86)
	at hudson.plugins.cygpath.CygpathLauncherDecorator$1.launch(CygpathLauncherDecorator.java:65)
	at hudson.Launcher$ProcStarter.start(Launcher.java:455)
	at hudson.Launcher$ProcStarter.join(Launcher.java:466)
	at ru.yandex.qatools.allure.jenkins.ReportBuilder.build(ReportBuilder.java:56)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:312)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:231)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:79)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1843)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
```

**Comment by snowymike** [comment]
haven't heard anything on this item since i submitted it in january.  am i reporting this issue to the correct place?  is it a requirement that Cygwin be installed on Windows slaves, even though allure.bat is installed with the Allure Commandline?  any configuration settings i may need to tweak on the slave or in Jenkins to avoid Allure trying to use Cygwin?  thanks.

**Comment by snowymike** [comment]
i ended up installing https://www.cygwin.com/setup-x86_64.exe on the Windows slave, then running Cygwin64 Terminal on the desktop once, then all the allure integration worked.  so it does appear to me that Cygwin should be called out as an explicit dependency on Windows.  it's still possible there was some configuration setting i had wrong on the slave or in Jenkins that made the plugin think Cygwin should be used, but i couldn't find such a setting.

**Comment by nikhilo** [comment]
I'm seeing this problem with my Jenkins setup.
Although, I'm already running my JNLP connect command from the Cygwin Shell 🤔 
And this is the error that I see,

```
ERROR: Step ‘Allure Report’ aborted due to exception: 
hudson.util.jna.JnaException: Win32 error: 2 - null
	at hudson.util.jna.RegistryKey.check(RegistryKey.java:120)
	at hudson.util.jna.RegistryKey.open(RegistryKey.java:215)
	at hudson.util.jna.RegistryKey.openReadonly(RegistryKey.java:210)
	at hudson.plugins.cygpath.CygpathLauncherDecorator$GetCygpathTask.getCygwinRoot(CygpathLauncherDecorator.java:127)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 10.0.12.182/10.0.12.182:19658
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1788)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:998)
		at hudson.plugins.cygpath.CygpathLauncherDecorator$1.getCygpathExe(CygpathLauncherDecorator.java:104)
		at hudson.plugins.cygpath.CygpathLauncherDecorator$1.cygpath(CygpathLauncherDecorator.java:86)
		at hudson.plugins.cygpath.CygpathLauncherDecorator$1.launch(CygpathLauncherDecorator.java:65)
		at hudson.Launcher$ProcStarter.start(Launcher.java:454)
		at hudson.Launcher$ProcStarter.join(Launcher.java:465)
		at ru.yandex.qatools.allure.jenkins.ReportBuilder.build(ReportBuilder.java:56)
		at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:312)
		at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:231)
		at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
		at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
		at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
		at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
		at hudson.model.Build$BuildExecution.post2(Build.java:186)
		at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
		at hudson.model.Run.execute(Run.java:1905)
		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
		at hudson.model.ResourceController.execute(ResourceController.java:97)
		at hudson.model.Executor.run(Executor.java:428)
Caused: hudson.util.IOException2: Failed to locate Cygwin installation. Is Cygwin installed?
	at hudson.plugins.cygpath.CygpathLauncherDecorator$GetCygpathTask.getCygwinRoot(CygpathLauncherDecorator.java:138)
	at hudson.plugins.cygpath.CygpathLauncherDecorator$GetCygpathTask.call(CygpathLauncherDecorator.java:142)
	at hudson.plugins.cygpath.CygpathLauncherDecorator$GetCygpathTask.call(CygpathLauncherDecorator.java:112)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:117)
	at java.lang.Thread.run(Unknown Source)
```

And this is what I see on the Cygwin Shell on the slave
```
Aug 25, 2020 5:10:01 PM hudson.Util getWin32ErrorMessage
WARNING: Failed to find resource bundle
java.util.MissingResourceException: Can't find bundle for base name /hudson/win32errors, locale en_US
        at java.util.ResourceBundle.throwMissingResourceException(Unknown Source)
        at java.util.ResourceBundle.getBundleImpl(Unknown Source)
        at java.util.ResourceBundle.getBundle(Unknown Source)
        at hudson.Util.getWin32ErrorMessage(Util.java:461)
        at hudson.util.jna.JnaException.<init>(JnaException.java:37)
        at hudson.util.jna.RegistryKey.check(RegistryKey.java:120)
        at hudson.util.jna.RegistryKey.open(RegistryKey.java:215)
        at hudson.util.jna.RegistryKey.openReadonly(RegistryKey.java:210)
        at hudson.plugins.cygpath.CygpathLauncherDecorator$GetCygpathTask.getCygwinRoot(CygpathLauncherDecorat
or.java:117)
        at hudson.plugins.cygpath.CygpathLauncherDecorator$GetCygpathTask.call(CygpathLauncherDecorator.java:1
42)
        at hudson.plugins.cygpath.CygpathLauncherDecorator$GetCygpathTask.call(CygpathLauncherDecorator.java:1
12)
        at hudson.remoting.UserRequest.perform(UserRequest.java:211)
        at hudson.remoting.UserRequest.perform(UserRequest.java:54)
        at hudson.remoting.Request$2.run(Request.java:369)
        at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:117)
        at java.lang.Thread.run(Unknown Source)

Aug 25, 2020 5:10:01 PM hudson.Util getWin32ErrorMessage
WARNING: Failed to find resource bundle
java.util.MissingResourceException: Can't find bundle for base name /hudson/win32errors, locale en_US
        at java.util.ResourceBundle.throwMissingResourceException(Unknown Source)
        at java.util.ResourceBundle.getBundleImpl(Unknown Source)
        at java.util.ResourceBundle.getBundle(Unknown Source)
        at hudson.Util.getWin32ErrorMessage(Util.java:461)
        at hudson.util.jna.JnaException.<init>(JnaException.java:37)
        at hudson.util.jna.RegistryKey.check(RegistryKey.java:120)
        at hudson.util.jna.RegistryKey.open(RegistryKey.java:215)
        at hudson.util.jna.RegistryKey.openReadonly(RegistryKey.java:210)
        at hudson.plugins.cygpath.CygpathLauncherDecorator$GetCygpathTask.getCygwinRoot(CygpathLauncherDecorat
or.java:127)
        at hudson.plugins.cygpath.CygpathLauncherDecorator$GetCygpathTask.call(CygpathLauncherDecorator.java:1
42)
        at hudson.plugins.cygpath.CygpathLauncherDecorator$GetCygpathTask.call(CygpathLauncherDecorator.java:1
12)
        at hudson.remoting.UserRequest.perform(UserRequest.java:211)
        at hudson.remoting.UserRequest.perform(UserRequest.java:54)
        at hudson.remoting.Request$2.run(Request.java:369)
        at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:117)
        at java.lang.Thread.run(Unknown Source)

Aug 25, 2020 5:10:01 PM hudson.Util getWin32ErrorMessage
WARNING: Failed to find resource bundle
java.util.MissingResourceException: Can't find bundle for base name /hudson/win32errors, locale en_US
        at java.util.ResourceBundle.throwMissingResourceException(Unknown Source)
        at java.util.ResourceBundle.getBundleImpl(Unknown Source)
        at java.util.ResourceBundle.getBundle(Unknown Source)
        at hudson.Util.getWin32ErrorMessage(Util.java:461)
        at hudson.util.jna.JnaException.<init>(JnaException.java:37)
        at hudson.util.jna.RegistryKey.check(RegistryKey.java:120)
        at hudson.util.jna.RegistryKey.open(RegistryKey.java:215)
        at hudson.util.jna.RegistryKey.openReadonly(RegistryKey.java:210)
        at hudson.plugins.cygpath.CygpathLauncherDecorator$GetCygpathTask.getCygwinRoot(CygpathLauncherDecorat
or.java:117)
        at hudson.plugins.cygpath.CygpathLauncherDecorator$GetCygpathTask.call(CygpathLauncherDecorator.java:1
42)
        at hudson.plugins.cygpath.CygpathLauncherDecorator$GetCygpathTask.call(CygpathLauncherDecorator.java:1
12)
        at hudson.remoting.UserRequest.perform(UserRequest.java:211)
        at hudson.remoting.UserRequest.perform(UserRequest.java:54)
        at hudson.remoting.Request$2.run(Request.java:369)
        at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:117)
        at java.lang.Thread.run(Unknown Source)

Aug 25, 2020 5:10:01 PM hudson.Util getWin32ErrorMessage
WARNING: Failed to find resource bundle
java.util.MissingResourceException: Can't find bundle for base name /hudson/win32errors, locale en_US
        at java.util.ResourceBundle.throwMissingResourceException(Unknown Source)
        at java.util.ResourceBundle.getBundleImpl(Unknown Source)
        at java.util.ResourceBundle.getBundle(Unknown Source)
        at hudson.Util.getWin32ErrorMessage(Util.java:461)
        at hudson.util.jna.JnaException.<init>(JnaException.java:37)
        at hudson.util.jna.RegistryKey.check(RegistryKey.java:120)
        at hudson.util.jna.RegistryKey.open(RegistryKey.java:215)
        at hudson.util.jna.RegistryKey.openReadonly(RegistryKey.java:210)
        at hudson.plugins.cygpath.CygpathLauncherDecorator$GetCygpathTask.getCygwinRoot(CygpathLauncherDecorat
or.java:127)
        at hudson.plugins.cygpath.CygpathLauncherDecorator$GetCygpathTask.call(CygpathLauncherDecorator.java:1
42)
        at hudson.plugins.cygpath.CygpathLauncherDecorator$GetCygpathTask.call(CygpathLauncherDecorator.java:1
12)
        at hudson.remoting.UserRequest.perform(UserRequest.java:211)
        at hudson.remoting.UserRequest.perform(UserRequest.java:54)
        at hudson.remoting.Request$2.run(Request.java:369)
        at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:117)
        at java.lang.Thread.run(Unknown Source)
```
(I also tried to rename the `allure` script to `allure.xyz` and got a relevant error. `java.io.IOException: Can't find allure commandline <null>`)

Since I'm already running in the Cygwin shell, I'm not sure what to try next.

**Comment by snowymike** [comment]
for me, i periodically have to kill the Jenkins slave process and restart it, as my original error reappears periodically for unknown reason.  my slave runs on Windows, so I just close the window that opens when the slave is running and double click the jnlp file to restart it.

i also had to manually run the Cygwin64 Terminal shortcut on the desktop once before things started working when i was first setting things up.
