### ISSUE TITLE
Pipeline Error plugin 

### ISSUE THREAD

**Issue by azheval** [jenkinsci/allure-plugin#230]
### Context
- **Jenkins version**: 2.150.2
- **Job type**: Pipeline

- **Allure plugin version**: 2.27
- **Allure commandline version**: 2.9

### Problem description

[Pipeline] // stage
[Pipeline] }
[KA_NightBuild] $ E:\Jenkins\Slave1\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\C_Commons_Rep_allure_bin_\bin\allure.bat generate "E:\Jenkins\Slave1\workspace\KA_NightBuild\allure-results\Начальное заполнение информационной базы" "E:\Jenkins\Slave1\workspace\KA_NightBuild\allure-results\Обновление информационной базы при переходе на новую версию" "E:\Jenkins\Slave1\workspace\KA_NightBuild\allure-results\Проверка открытия печатных форм Администратор" "E:\Jenkins\Slave1\workspace\KA_NightBuild\allure-results\Проверка открытия печатных форм Бухгалтер Гладилина" "E:\Jenkins\Slave1\workspace\KA_NightBuild\allure-results\Проверка открытия печатных форм Производство Трудолюбов" "E:\Jenkins\Slave1\workspace\KA_NightBuild\allure-results\Проверка открытия форм созданием Администратор Федоров" "E:\Jenkins\Slave1\workspace\KA_NightBuild\allure-results\Проверка открытия форм созданием Бухгалтер Гладилина" "E:\Jenkins\Slave1\workspace\KA_NightBuild\allure-results\Проверка открытия форм созданием Кладовщик Волков" "E:\Jenkins\Slave1\workspace\KA_NightBuild\allure-results\Проверка открытия форм созданием Менеджер по закупкам Королев" "E:\Jenkins\Slave1\workspace\KA_NightBuild\allure-results\Проверка открытия форм созданием Менеджер по продажам Васечкин" "E:\Jenkins\Slave1\workspace\KA_NightBuild\allure-results\Проверка открытия форм созданием Петрищев Руководитель отдела продаж" "E:\Jenkins\Slave1\workspace\KA_NightBuild\allure-results\Проверка открытия форм созданием Толчеева Маркетолог" "E:\Jenkins\Slave1\workspace\KA_NightBuild\allure-results\Проверка открытия форм созданием Трудолюбов Производство" "E:\Jenkins\Slave1\workspace\KA_NightBuild\allure-results\Проверка сервисов ИТС Администратор Федоров" -c -o E:\Jenkins\Slave1\workspace\KA_NightBuild\allure-report
���誮� ������� �室��� ��ப�.
�訡�� � ᨭ⠪�� �������.
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ru.yandex.qatools.allure.jenkins.exception.AllurePluginException: Can not generate Allure Report, exit code: 255
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:296)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:218)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Finished: FAILURE

**Comment by LIMPIX31** [comment]
Ну впринципе да

**Comment by LIMPIX31** [comment]
Абсалютна сагласин
