### ISSUE TITLE
New config field doesn't honor blank value

### ISSUE THREAD

**Issue by kluke0** [jenkinsci/allure-plugin#232]
### Context
- **Jenkins version**: 2.138.1
- **Job type**: Freestyle

- **Allure plugin version**: 2.28
- **Allure CLI version**: 2.6.0

### Problem description

New field for config.yml causes SnakeYAML to throw "IsDirectory" exception when the field is left blank.

In the logs provided below, I pass nothing at all to the new config field under Advanced.  When the job is run, the command line builder is adding a --config as the current workspace, instead of leaving it blank: --config /srv/jenkins_home/jobs/My_Job/workspace

### Logs & Traces

[workspace] $ /srv/jenkins_home/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/Allure/bin/allure generate -c -o /srv/jenkins_home/jobs/My_Job/workspace/allure-report --config /srv/jenkins_home/jobs/My_Job/workspace
Exception in thread "main" org.yaml.snakeyaml.error.YAMLException: java.io.IOException: Is a directory
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:254)
	at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:58)
	at com.fasterxml.jackson.dataformat.yaml.YAMLParser.<init>(YAMLParser.java:154)
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory._createParser(YAMLFactory.java:420)
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:321)
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:14)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3058)
	at io.qameta.allure.config.ConfigLoader.load(ConfigLoader.java:34)
	at java.util.Optional.map(Optional.java:215)
	at io.qameta.allure.Commands.getConfig(Commands.java:51)
	at io.qameta.allure.Commands.createReportConfiguration(Commands.java:175)
	at io.qameta.allure.Commands.generate(Commands.java:88)
	at io.qameta.allure.CommandLine.run(CommandLine.java:129)
	at java.util.Optional.orElseGet(Optional.java:267)
	at io.qameta.allure.CommandLine.main(CommandLine.java:72)
Caused by: java.io.IOException: Is a directory
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:46)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:159)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
	at com.fasterxml.jackson.dataformat.yaml.UTF8Reader.readBytes(UTF8Reader.java:327)
	at com.fasterxml.jackson.dataformat.yaml.UTF8Reader.loadMore(UTF8Reader.java:447)
	at com.fasterxml.jackson.dataformat.yaml.UTF8Reader.read(UTF8Reader.java:185)
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:223)
	... 14 more
ERROR: Build step failed with exception
ru.yandex.qatools.allure.jenkins.exception.AllurePluginException: Can not generate Allure Report, exit code: 1
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:315)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:229)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1840)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Allure Report' marked build as failure
Finished: FAILURE

**Comment by YoninL** [comment]
Same issue here, have to rollback to 2.27.

**Comment by mgarzone** [comment]
The same problem happened with our build. Rollbacking to previous version 2.27. cleared the issue.
