### ISSUE TITLE
Can not generate Allure Report, exit code: 126

### ISSUE THREAD

**Issue by sharly2012** [jenkinsci/allure-plugin#242]
### Context
- **Jenkins version**: 2.182
- **Job type**: Freestyle

- **Allure plugin version**: 2.28.1
- **Allure commandline version**: 2.12.1

### Problem description
It can't generate the report in jenkins, but if I copy the same allure command to Terminal, it can generate the report successfully.

### Logs & Traces

web_automation] $ /Users/admin/allure/bin/allure generate /Users/admin/.jenkins/workspace/web_automation/target/allure-results -c -o /Users/admin/.jenkins/workspace/web_automation/allure-report
env: sh: Not a directory
ERROR: Build step failed with exception
ru.yandex.qatools.allure.jenkins.exception.AllurePluginException: Can not generate Allure Report, exit code: 126
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:314)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:231)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:79)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1843)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Allure Report' marked build as failure
Finished: FAILURE

**Comment by sharly2012** [comment]
I had resolved it by change the jenkins config setting.

**Comment by pligor** [comment]
"I had resolved it by change the jenkins config setting." What did you changed exactly in order to solve it ?

**Comment by jhonata-santos** [comment]
What have you changed please?

**Comment by deepirms2619** [comment]
any update on how this issue was resolved, even i'm encountering the same issue?

**Comment by NewbieProger** [comment]
@sharly2012 HELLLO?!?!?!?

**Comment by NewbieProger** [comment]
Hi. I solved it rebase .jenkins directory. Follow here http://tech.nitoyon.com/en/blog/2014/02/25/jenkins-home-win/

**Comment by burtsevyg** [comment]
Same problem.
