### ISSUE TITLE
Allure report sometimes generate failed with exception

### ISSUE THREAD

**Issue by benjaminliugang** [jenkinsci/allure-plugin#251]
### Context
- **Jenkins version**: 2.164.2
- **Job type**: Matrix

- **Allure plugin version**: 2.28.1

### Problem description
Allure report generate failed with below exception

### Logs & Traces
`
07:52:19 Creating artifact for the build.
07:57:04 ERROR: Step ï¿½Allure Reportï¿½ aborted due to exception: 
07:57:04 java.lang.InterruptedException
07:57:04 	at java.lang.Object.wait(Native Method)
07:57:04 	at hudson.remoting.Request.call(Request.java:177)
07:57:04 	at hudson.remoting.Channel.call(Channel.java:956)
07:57:04 	at hudson.FilePath.act(FilePath.java:1069)
07:57:04 	at hudson.FilePath.act(FilePath.java:1058)
07:57:04 	at hudson.FilePath.archive(FilePath.java:482)
07:57:04 	at hudson.FilePath.archive(FilePath.java:512)
07:57:04 	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.saveAllureArtifact(AllureReportPublisher.java:334)
07:57:04 	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:317)
07:57:04 	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:231)
07:57:04 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
07:57:04 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
07:57:04 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
07:57:04 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
07:57:04 	at hudson.model.Build$BuildExecution.post2(Build.java:186)
07:57:04 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
07:57:04 	at hudson.model.Run.execute(Run.java:1841)
07:57:04 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
07:57:04 	at hudson.model.ResourceController.execute(ResourceController.java:97)
07:57:04 	at hudson.model.Executor.run(Executor.java:429)
`

**Comment by UladzislauValchkou** [comment]
We are facing similar issue, Allure report randomly fails with following stacktrace


  ```
      java.lang.InterruptedException
	      at java.base/java.lang.Object.wait(Native Method)
	      at hudson.remoting.Request$1.get(Request.java:317)
	      at hudson.remoting.Request$1.get(Request.java:240)
	      at hudson.remoting.FutureAdapter.get(FutureAdapter.java:65)
	      at io.qameta.allure.jenkins.AllureUploader.stopUploader(AllureUploader.java:190)
	      at io.qameta.allure.jenkins.WithAllureUploadStep$StopUploadCallback.finished(WithAllureUploadStep.java:210)
	      at org.jenkinsci.plugins.workflow.steps.BodyExecutionCallback$TailCall.onSuccess(BodyExecutionCallback.java:118)
	      at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution$SuccessAdapter.receive(CpsBodyExecution.java:377)
	      at com.cloudbees.groovy.cps.impl.ForLoopBlock$ContinuationImpl.loopCond(ForLoopBlock.java:50)
	      at jdk.internal.reflect.GeneratedMethodAccessor1060.invoke(Unknown Source)
	      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	      at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	      at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	      at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:89)
	      at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
	      at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
	      at jdk.internal.reflect.GeneratedMethodAccessor184.invoke(Unknown Source)
	      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	      at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	      at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	      at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:76)
	      at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
         	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:66)
         	at jdk.internal.reflect.GeneratedMethodAccessor285.invoke(Unknown Source)
	 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	 	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	 	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	 	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	 	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	 	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	 	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	 	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	 	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	 	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	 	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	 	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
	 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:400)
	 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)
	 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:312)
	 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:276)
	 	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
	 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	 	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
	 	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	 	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	 	at java.base/java.lang.Thread.run(Thread.java:829)
```


**Jenkins version**: 2.289.2
**Allure plugin version**: 2.29.0

**Comment by cheshi-mantu** [comment]
> We are facing similar issue, Allure report randomly fails with following stacktrace
> 
> ```
>     java.lang.InterruptedException
>         at java.base/java.lang.Object.wait(Native Method)
>         at hudson.remoting.Request$1.get(Request.java:317)
>         at hudson.remoting.Request$1.get(Request.java:240)
>         at hudson.remoting.FutureAdapter.get(FutureAdapter.java:65)
>         at io.qameta.allure.jenkins.AllureUploader.stopUploader(AllureUploader.java:190)
>         at io.qameta.allure.jenkins.WithAllureUploadStep$StopUploadCallback.finished(WithAllureUploadStep.java:210)
>         at org.jenkinsci.plugins.workflow.steps.BodyExecutionCallback$TailCall.onSuccess(BodyExecutionCallback.java:118)
>         at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution$SuccessAdapter.receive(CpsBodyExecution.java:377)
>         at com.cloudbees.groovy.cps.impl.ForLoopBlock$ContinuationImpl.loopCond(ForLoopBlock.java:50)
>         at jdk.internal.reflect.GeneratedMethodAccessor1060.invoke(Unknown Source)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
>         at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
>         at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:89)
>         at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
>         at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
>         at jdk.internal.reflect.GeneratedMethodAccessor184.invoke(Unknown Source)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
>         at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
>         at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:76)
>         at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
>        	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:66)
>        	at jdk.internal.reflect.GeneratedMethodAccessor285.invoke(Unknown Source)
>    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>    	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
>    	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
>    	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
>    	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
>    	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
>    	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
>    	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
>    	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
>    	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
>    	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
>    	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
>    	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
>    	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:400)
>    	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)
>    	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:312)
>    	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:276)
>    	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
>    	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
>    	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
>    	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
>    	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
>    	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
>    	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
>    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>    	at java.base/java.lang.Thread.run(Thread.java:829)
> ```
> 
> **Jenkins version**: 2.289.2
> **Allure plugin version**: 2.29.0

This doesn't look like Allure report plug-in, more like Allure TestOps plug-in (io.qameta.allure.jenkins.AllureUploader.stopUploader(AllureUploader.java:190) or WithAllureUploadStep), which is supported via qameta's service desk https://support.qameta.io
