### ISSUE TITLE
NullPointerException at AllureReportPublisherDescriptor.java:112

### ISSUE THREAD

**Issue by brailovskiy** [jenkinsci/allure-plugin#256]
### Context
- **Jenkins version**: 2.114
- **Job type**: Pipeline, node.

- **Allure plugin version**: 2.28.1
- **Allure commandline version**: 2.13.0

### Problem description

_Describe your problem in a meaningful way_:
I've tried to start my pipeline and got NPE, no idea what i'm doing wrong
reinstalling allure and allure CLI, change JDK and path have no effect

### Logs & Traces

`java.lang.NullPointerException
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisherDescriptor.getCommandlineInstallation(AllureReportPublisherDescriptor.java:112)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.getCommandline(AllureReportPublisher.java:346)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:303)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:231)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by vijaynagr** [comment]
Is something happening on this issue? Has any one figured any solution for this issue?
