### ISSUE TITLE
ERROR: Step ‘Allure Report’ aborted due to exception:  java.nio.file.AccessDeniedException

### ISSUE THREAD

**Issue by teamdts** [jenkinsci/allure-plugin#263]
### Context
- **Jenkins version**:  2.222.3
- **Job type**: Freestyle

- **Allure plugin version**: 2.28.1
- **Allure commandline version**: 2.13.3

### Problem description

_Describe your problem in a meaningful way_:
  allure report not generated successfully based on result directory to report directory.

- what were you doing : generating allure report in post build action
- what was expected : successfully generated from result dir to report directory.
- what occurred finally :  now some how testrun.json file is trying to finding but in result directory lots of .json file name and start with different names of each test cases. 

### Logs & Traces

```
ERROR: Step ‘Allure Report’ aborted due to exception: 
java.nio.file.AccessDeniedException: /var/lib/jenkins/workspace/UI-TEST-local-firefox/MyProject/reports/testrun.json
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
	at java.base/java.nio.file.Files.newOutputStream(Files.java:219)
	at java.base/java.nio.file.Files.newBufferedWriter(Files.java:2919)
	at ru.yandex.qatools.allure.jenkins.callables.AbstractAddInfo.invoke(AbstractAddInfo.java:26)
	at ru.yandex.qatools.allure.jenkins.callables.AbstractAddInfo.invoke(AbstractAddInfo.java:19)
	at hudson.FilePath.act(FilePath.java:1075)
	at hudson.FilePath.act(FilePath.java:1058)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.addTestRunInfo(AllureReportPublisher.java:399)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.prepareResults(AllureReportPublisher.java:390)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:230)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1881)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)
Finished: FAILURE
```
![2](https://user-images.githubusercontent.com/63253499/83238740-7e196480-a1b4-11ea-9941-e3264d363836.png)

_Please include any relevant log that could serve to better understand the source of your issue_
![1](https://user-images.githubusercontent.com/63253499/83239083-f2540800-a1b4-11ea-9a89-f1b3324493b2.png)

**Comment by kotprav** [comment]
Hello @teamdts, have you fixed this issue? If yes, could you please tell me how? Thanks!

**Comment by mshonichev** [comment]
have same issue with latest Allure (2.14.0). Any hints on workaround?

**Comment by NwawelAIroume** [comment]
> have same issue with Allure plugin 2.28.1 and latest Allure Commandline (2.14.0). Any hints on workaround?

I had a similar issue.
I noticed that other linux users have no right to write on folder allure-results/
`ls -l ` --> drwxrwxr-x  2 mchine  mchine   4096 Jul  1 14:09  allure-results

I fixed it with `chmod o+w allure-results/`
