### ISSUE TITLE
AllurePluginException: Can not generate Allure Report, exit code: 127

### ISSUE THREAD

**Issue by deepirms2619** [jenkinsci/allure-plugin#265]
### Context
- **Jenkins version**:  2.222.4
- **Job type**: Freestyle

- **Allure commandline version**: 2.13.3

### Problem description

_Describe your problem in a meaningful way_:
- what were you doing:

I'm trying to integrate Jenkins with Allure Report, but receiving an exception.

- Installed allure plugin 
- added Global Tool Configuration with 'Allure Commandline installations'

Actual: **AllurePluginException: Can not generate Allure Report, exit code: 127**

### Logs & Traces

========================== 4 passed in 44.04 seconds ===========================
[Test-Python] $ /Users/deepirms/.jenkins/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/allure/bin/allure generate -c -o /Users/deepirms/.jenkins/workspace/Test-Python/allure-report
env: sh: No such file or directory
ERROR: Build step failed with exception
ru.yandex.qatools.allure.jenkins.exception.AllurePluginException: Can not generate Allure Report, exit code: 127
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:314)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:231)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1881)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)
Build step 'Allure Report' marked build as failure
Finished: FAILURE

**Comment by deepirms2619** [comment]
Opened by mistake

**Comment by NewbieProger** [comment]
Hi. I solved it rebase .jenkins directory. Follow here http://tech.nitoyon.com/en/blog/2014/02/25/jenkins-home-win/
