### ISSUE TITLE
Allure report generation has stopped working in Jenkins (unable to download allure-commandline-2.8.1.zip)

### ISSUE THREAD

**Issue by vanangelov** [jenkinsci/allure-plugin#274]
### Context
- **Jenkins version**:  2.223
- **Job type**: Freestyle

- **Allure plugin version**: 2.28.1
- **Allure commandline version**: allure-commandline-2.8.1.zip

### Problem description

Generation of Jenkins allure reports has stopped working a few hours ago. Similar problem occurred yesterday (see #https://github.com/jenkinsci/allure-plugin/issues/273)

### Logs & Traces

```
ERROR: Step ‘Allure Report’ aborted due to exception: 
java.io.IOException: Server returned HTTP response code: 401 for URL: https://repo.jenkins-ci.org/maven-repo1/io/qameta/allure/allure-commandline/2.8.1/allure-commandline-2.8.1.zip
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:2982)
	at java.net.URLConnection.getHeaderFieldLong(URLConnection.java:629)
	at java.net.URLConnection.getContentLengthLong(URLConnection.java:501)
	at java.net.URLConnection.getContentLength(URLConnection.java:485)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentLength(HttpsURLConnectionImpl.java:398)
	at org.jvnet.robust_http_client.RetryableHttpStream.<init>(RetryableHttpStream.java:90)
```

**Comment by KLDM** [comment]
Fast solution [here](https://github.com/jenkinsci/allure-plugin/issues/273#issuecomment-712908011)

**Comment by halkeye** [comment]
> Fast solution [here](https://github.com/jenkinsci/allure-plugin/issues/273#issuecomment-712908011)

s/Fast/Proper/

**Comment by jglick** [comment]
Should be fixed by https://github.com/jenkins-infra/crawler/pull/92.

**Comment by otec-petr** [comment]
Still reproduced

**Comment by jglick** [comment]
Might take a while for that change to propagate.

**Comment by daniel-beck** [comment]
Will need update center metadata to be updated, which happens about once a day or when you click "Check Now" in plugin manager.

**Comment by otec-petr** [comment]
Working, could be closed
