### ISSUE TITLE
Serialization of AllureCommandlineInstallation extends ToolInstallation over Remoting is deprecated

### ISSUE THREAD

**Issue by PayBas** [jenkinsci/allure-plugin#284]
### Version report

Jenkins and plugins versions report:
```
Jenkins: 2.277.1
OS: Linux - 5.10.22-100.fc32.x86_64
---
pipeline-graph-analysis:1.10
durable-task:1.35
favorite:2.3.3
credentials-binding:1.24
workflow-multibranch:2.23
workflow-durable-task-step:2.38
lockable-resources:2.10
blueocean-jwt:1.24.5
pipeline-model-api:1.8.4
credentials:2.3.15
docker-workflow:1.26
blueocean-commons:1.24.5
workflow-job:2.40
sse-gateway:1.24
branch-api:2.6.3
pipeline-input-step:2.12
matrix-project:1.18
workflow-cps:2.90
mercurial:2.14
checks-api:1.6.1
workflow-scm-step:2.12
docker-commons:1.17
cloudbees-bitbucket-branch-source:2.9.5-SNAPSHOT (private-b3d1ee04-isc75124)
echarts-api:5.0.1-1
okhttp-api:3.14.9
script-security:1.76
global-build-stats:1.5
junit:1.49
pipeline-build-step:2.13
dark-theme:0.0.12
trilead-api:1.0.13
allure-jenkins-plugin:2.29.0
jira:3.2.1
workflow-basic-steps:2.23
jquery:1.12.4-1
resource-disposer:0.15
blueocean-i18n:1.24.5
theme-manager:0.6
ace-editor:1.1
groovy:2.3
blueocean-git-pipeline:1.24.5
ansicolor:0.7.5
blueocean-core-js:1.24.5
git-server:1.9
handy-uri-templates-2-api:2.1.8-1.0
blueocean-config:1.24.5
jenkins-design-language:1.24.5
dependency-check-jenkins-plugin:5.1.1
pipeline-milestone-step:1.3.2
bootstrap4-api:4.6.0-2
jquery3-api:3.5.1-3
blueocean:1.24.5
git:4.7.0
pipeline-rest-api:2.19
structs:1.22
ssh-agent:1.22
plugin-util-api:2.1.0
pipeline-model-definition:1.8.4
ws-cleanup:0.39
jackson2-api:2.12.1
matrix-auth:2.6.6
htmlpublisher:1.25
handlebars:3.0.8
blueocean-rest-impl:1.24.5
workflow-api:2.42
blueocean-pipeline-editor:1.24.5
pipeline-stage-view:2.19
scm-api:2.6.4
pubsub-light:1.13
popper-api:1.16.1-2
pipeline-model-extensions:1.8.4
git-client:3.7.0
github-api:1.123
workflow-step-api:2.23
pipeline-stage-step:2.5
authentication-tokens:1.4
pipeline-utility-steps:2.7.0
jsch:0.1.55.2
momentjs:1.1.1
apache-httpcomponents-client-4-api:4.5.13-1.0
blueocean-personalization:1.24.5
blueocean-dashboard:1.24.5
blueocean-autofavorite:1.2.4
snakeyaml-api:1.27.0
command-launcher:1.5
pipeline-stage-tags-metadata:1.8.4
token-macro:2.15
nexus-jenkins-plugin:3.11.20210323-112924.daaeac7
bouncycastle-api:2.20
sonar:2.13
blueocean-jira:1.24.5
workflow-aggregator:2.6
blueocean-rest:1.24.5
audit-trail:3.8
mailer:1.34
display-url-api:2.3.4
javadoc:1.6
ssh-credentials:1.18.1
blueocean-pipeline-api-impl:1.24.5
antisamy-markup-formatter:2.1
blueocean-github-pipeline:1.24.5
workflow-cps-global-lib:2.18
jdk-tool:1.5
variant:1.4
blueocean-web:1.24.5
blueocean-pipeline-scm-api:1.24.5
blueocean-bitbucket-pipeline:1.24.5
github:1.33.1
jquery-detached:1.2.1
cloudbees-folder:6.15
active-directory:2.23
blueocean-events:1.24.5
timestamper:1.12
font-awesome-api:5.15.2-2
github-branch-source:2.10.2
build-monitor-plugin:1.12+build.201809061734
blueocean-display-url:2.4.1
jjwt-api:0.11.2-9.c8b45b8bb173
workflow-support:3.8
plain-credentials:1.7
Result: [Plugin:pipeline-graph-analysis, Plugin:durable-task, Plugin:favorite, Plugin:credentials-binding, Plugin:workflow-multibranch, Plugin:workflow-durable-task-step, Plugin:lockable-resources, Plugin:blueocean-jwt, Plugin:pipeline-model-api, Plugin:credentials, Plugin:docker-workflow, Plugin:blueocean-commons, Plugin:workflow-job, Plugin:sse-gateway, Plugin:branch-api, Plugin:pipeline-input-step, Plugin:matrix-project, Plugin:workflow-cps, Plugin:mercurial, Plugin:checks-api, Plugin:workflow-scm-step, Plugin:docker-commons, Plugin:cloudbees-bitbucket-branch-source, Plugin:echarts-api, Plugin:okhttp-api, Plugin:script-security, Plugin:global-build-stats, Plugin:junit, Plugin:pipeline-build-step, Plugin:dark-theme, Plugin:trilead-api, Plugin:allure-jenkins-plugin, Plugin:jira, Plugin:workflow-basic-steps, Plugin:jquery, Plugin:resource-disposer, Plugin:blueocean-i18n, Plugin:theme-manager, Plugin:ace-editor, Plugin:groovy, Plugin:blueocean-git-pipeline, Plugin:ansicolor, Plugin:blueocean-core-js, Plugin:git-server, Plugin:handy-uri-templates-2-api, Plugin:blueocean-config, Plugin:jenkins-design-language, Plugin:dependency-check-jenkins-plugin, Plugin:pipeline-milestone-step, Plugin:bootstrap4-api, Plugin:jquery3-api, Plugin:blueocean, Plugin:git, Plugin:pipeline-rest-api, Plugin:structs, Plugin:ssh-agent, Plugin:plugin-util-api, Plugin:pipeline-model-definition, Plugin:ws-cleanup, Plugin:jackson2-api, Plugin:matrix-auth, Plugin:htmlpublisher, Plugin:handlebars, Plugin:blueocean-rest-impl, Plugin:workflow-api, Plugin:blueocean-pipeline-editor, Plugin:pipeline-stage-view, Plugin:scm-api, Plugin:pubsub-light, Plugin:popper-api, Plugin:pipeline-model-extensions, Plugin:git-client, Plugin:github-api, Plugin:workflow-step-api, Plugin:pipeline-stage-step, Plugin:authentication-tokens, Plugin:pipeline-utility-steps, Plugin:jsch, Plugin:momentjs, Plugin:apache-httpcomponents-client-4-api, Plugin:blueocean-personalization, Plugin:blueocean-dashboard, Plugin:blueocean-autofavorite, Plugin:snakeyaml-api, Plugin:command-launcher, Plugin:pipeline-stage-tags-metadata, Plugin:token-macro, Plugin:nexus-jenkins-plugin, Plugin:bouncycastle-api, Plugin:sonar, Plugin:blueocean-jira, Plugin:workflow-aggregator, Plugin:blueocean-rest, Plugin:audit-trail, Plugin:mailer, Plugin:display-url-api, Plugin:javadoc, Plugin:ssh-credentials, Plugin:blueocean-pipeline-api-impl, Plugin:antisamy-markup-formatter, Plugin:blueocean-github-pipeline, Plugin:workflow-cps-global-lib, Plugin:jdk-tool, Plugin:variant, Plugin:blueocean-web, Plugin:blueocean-pipeline-scm-api, Plugin:blueocean-bitbucket-pipeline, Plugin:github, Plugin:jquery-detached, Plugin:cloudbees-folder, Plugin:active-directory, Plugin:blueocean-events, Plugin:timestamper, Plugin:font-awesome-api, Plugin:github-branch-source, Plugin:build-monitor-plugin, Plugin:blueocean-display-url, Plugin:jjwt-api, Plugin:workflow-support, Plugin:plain-credentials]
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Fedora 32
```

### Reproduction steps

Not sure since when these warnings started appearing. Perhaps after updating to Jenkins: 2.277.1
Doesn't matter how Allure is configured under Global Tool Configuration. Tried a couple different methods/urls.
Below logs show up every couple of minutes or so.

Doesn't appear to have any affect on builds (yet).

### Results

Expected result:

No warnings in the Jenkins sytem log

Actual result:

```
Apr 04, 2021 6:25:10 PM WARNING hudson.tools.ToolInstallation writeReplace

Serialization of AllureCommandlineInstallation extends ToolInstallation over Remoting is deprecated
java.lang.Throwable
	at hudson.tools.ToolInstallation.writeReplace(ToolInstallation.java:236)
	at sun.reflect.GeneratedMethodAccessor9235.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeWriteReplace(ObjectStreamClass.java:1244)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1136)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at hudson.remoting.UserRequest._serialize(UserRequest.java:263)
	at hudson.remoting.UserRequest.serialize(UserRequest.java:272)
	at hudson.remoting.UserRequest.<init>(UserRequest.java:101)
	at hudson.remoting.Channel.call(Channel.java:999)
	at ru.yandex.qatools.allure.jenkins.utils.BuildUtils.setEnvVarsForNode(BuildUtils.java:48)
	at ru.yandex.qatools.allure.jenkins.utils.BuildUtils.setUpTool(BuildUtils.java:40)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.getCommandline(AllureReportPublisher.java:353)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:303)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:231)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:99)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:69)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by felipecrs** [comment]
This is appearing all the time in my Jenkins logs. It would be very good if it could be solved. :)

**Comment by PayBas** [comment]
Don't get your hopes up. This project is dead.

**Comment by an-nikolaev** [comment]
Is there at least some workaround to avoid these messages appearing in the log, because our Jenkins system log consists of 95% of them.

**Comment by RuStyC0der** [comment]
Hi there, got the same issue and also widget with result disappeared

**Comment by long76** [comment]
https://plugins.jenkins.io/allure-jenkins-plugin/releases/#version_2.34.0 GA with fix

**Comment by long76** [comment]
@skuznetsov-al need close

**Comment by baev** [comment]
fixed via https://github.com/jenkinsci/allure-plugin/pull/399
