### ISSUE TITLE
Allure report plugin randomly failes when generating reports

### ISSUE THREAD

**Issue by kamil1014** [jenkinsci/allure-plugin#313]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```
Jenkins 2.332.3

allure-jenkins-plugin:2.30.2
</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

[-](inbound-agent:4.10-3)

Dockerized on centos7

### Reproduction steps

Hi,

I have problem with allure test report generation. It sometimes failes without obvious reason (non of resources are missing (CPU and Memory)). It failes in jobs with only few tests and in those with thousands of them randomly (with no pattern)

Java Selenide tests

### Expected Results

Report is always generated

### Actual Results

There are two types of errors:

Unpacking ...
[maven.org/maven2/io/qameta/allure/allure-commandline/2.18.1/allure-commandline-2.18.1.zip](https://nexus-proxy.grupawp.pl/repository/maven.org/maven2/io/qameta/allure/allure-commandline/2.18.1/allure-commandline-2.18.1.zip) to /home/jenkins/agent/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/allure-2.18.1 on wakacje-automatic-tests-wak-regresja-436-zj3w8-z3k74-hw99r
[WAK_Regresja] $ /home/jenkins/agent/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/allure-2.18.1/allure-2.18.1/bin/allure generate /home/jenkins/agent/workspace/wakacje/automatic-tests/WAK_Regresja/allure-results -c -o /home/jenkins/agent/workspace/wakacje/automatic-tests/WAK_Regresja/allure-report[Pipeline] }[Pipeline] // script[Pipeline] }[Pipeline] // stage[Pipeline] }[Pipeline] // withEnv[Pipeline] }[Pipeline] // node[Pipeline] }[Pipeline] // podTemplate[Pipeline] End of Pipelinejava.nio.channels.ClosedChannelException
at org.jenkinsci.remoting.protocol.NetworkLayer.onRecvClosed(NetworkLayer.java:155)
at org.jenkinsci.remoting.protocol.impl.NIONetworkLayer.ready(NIONetworkLayer.java:143)
at org.jenkinsci.remoting.protocol.IOHub$OnReady.run(IOHub.java:789)
at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
Caused: java.io.IOException: Backing channel 'JNLP4-connect connection from pod-6.front-2.services.dc-2.srv.dcwp.pl/10.34.7.6:39708' is disconnected.
at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:215)
at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:285)
at com.sun.proxy.$Proxy98.isAlive(Unknown Source)
at hudson.Launcher$RemoteLauncher$ProcImpl.isAlive(Launcher.java:1215)
at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1207)
at hudson.Launcher$ProcStarter.join(Launcher.java:524)
at ru.yandex.qatools.allure.jenkins.ReportBuilder.build(ReportBuilder.java:56)
at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:312)
at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:231)
at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:101)
at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)

 

and the second one: 

 

[WAK_Regresja] $ /home/jenkins/agent/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/allure-2.18.1/allure-2.18.1/bin/allure generate /home/jenkins/agent/workspace/wakacje/automatic-tests/WAK_Regresja/allure-results -c -o /home/jenkins/agent/workspace/wakacje/automatic-tests/WAK_Regresja/allure-report
Report successfully generated to /home/jenkins/agent/workspace/wakacje/automatic-tests/WAK_Regresja/allure-report
Allure report was successfully generated.
Creating artifact for the build.[Pipeline] }[Pipeline] // script[Pipeline] }[Pipeline] // stage[Pipeline] }[Pipeline] // withEnv[Pipeline] }[Pipeline] // node[Pipeline] }[Pipeline] // podTemplate[Pipeline] End of Pipelinejava.nio.channels.ClosedChannelException
Also: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from pod-2.front-1.services.dc-2......pl/...:35144
at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1784)
at hudson.remoting.Request.call(Request.java:199)
at hudson.remoting.Channel.call(Channel.java:999)
at hudson.FilePath.act(FilePath.java:1194)
at hudson.FilePath.act(FilePath.java:1183)
at hudson.FilePath.archive(FilePath.java:515)
at hudson.FilePath.archive(FilePath.java:494)
at hudson.FilePath.archive(FilePath.java:552)
at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.saveAllureArtifact(AllureReportPublisher.java:334)
at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:317)
at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:231)
at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:101)
at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Caused: hudson.remoting.RequestAbortedException
at hudson.remoting.Request.abort(Request.java:345)
at hudson.remoting.Channel.terminate(Channel.java:1080)
at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:240)
at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecvClosed(ApplicationLayer.java:221)
at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:825)
at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:289)
at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:168)
at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:825)
at org.jenkinsci.remoting.protocol.NetworkLayer.onRecvClosed(NetworkLayer.java:155)
at org.jenkinsci.remoting.protocol.impl.NIONetworkLayer.ready(NIONetworkLayer.java:143)
at org.jenkinsci.remoting.protocol.IOHub$OnReady.run(IOHub.java:789)
at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by vbragin** [comment]
Sorry but we need some real steps to reproduce. Info that sometimes smth wrong happens - not so good( Such issue will stay in backlog forever.  
If you will provide the stability-problem description we will try to do our best to resolve it.
