### ISSUE TITLE
allure 2.9 - java.io.FileNotFoundException

### ISSUE THREAD

**Issue by eroshenkoam** [jenkinsci/allure-plugin#36]
ERROR: Build step failed with exception
javax.xml.bind.DataBindingException: javax.xml.bind.MarshalException
 - with linked exception:
[java.io.FileNotFoundException: /The configuration file provided by Jenkins (Keine Berechtigung)]
	at javax.xml.bind.JAXB._marshal(JAXB.java:574)
	at javax.xml.bind.JAXB.marshal(JAXB.java:408)
	at ru.yandex.qatools.allure.jenkins.callables.CreateEnvironment.invoke(CreateEnvironment.java:63)
	at ru.yandex.qatools.allure.jenkins.callables.CreateEnvironment.invoke(CreateEnvironment.java:23)
	at hudson.FilePath.act(FilePath.java:990)
	at hudson.FilePath.act(FilePath.java:968)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:169)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:93)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1047)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
	at hudson.model.Run.execute(Run.java:1763)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:531)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Caused by: javax.xml.bind.MarshalException
 - with linked exception:
[java.io.FileNotFoundException: /The configuration file provided by Jenkins (Keine Berechtigung)]
	at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.createXmlOutput(MarshallerImpl.java:215)
	at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.marshal(MarshallerImpl.java:236)
	at javax.xml.bind.JAXB._marshal(JAXB.java:572)
	... 16 more
Caused by: java.io.FileNotFoundException: /The configuration file provided by Jenkins (Keine Berechtigung)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.createXmlOutput(MarshallerImpl.java:210)
	... 18 more
Build step 'Allure Report' marked build as failure
Finished: FAILURE

**Comment by eroshenkoam** [comment]
fixed in 2.10
