### ISSUE TITLE
Null value not allowed as an environment variable: ALLURE_HOME

### ISSUE THREAD

**Issue by SubhashNikam** [jenkinsci/allure-plugin#39]
I followed document to set Allure Plugin in jenkins using Build agents have NOT connection to maven central steps. When my build is executed, I can see xml files generated but getting error below:

ERROR: Build step failed with exception
java.lang.IllegalArgumentException: Null value not allowed as an environment variable: ALLURE_HOME
	at hudson.EnvVars.put(EnvVars.java:356)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:179)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:93)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1037)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
	at hudson.model.Run.execute(Run.java:1763)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:529)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)

**Comment by eroshenkoam** [comment]
Jenkins had to pre-load tool. In the logs, it looks like this:
```
Unpacking https://oss.sonatype.org/content/repositories/releases/ru/yandex/qatools/allure/allure-commandline/1.4.19/allure-commandline-1.4.19-standalone.zip to /Users/eroshenkoam/Developer/jenkinsci/allure-plugin/work/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/1.4.19 on Jenkins
```

**Comment by SubhashNikam** [comment]
Thanks for inputs.
Now its working fine after I load command line tool to the plugins in Jenkins.
I am using Jenkins on windows extracted allure-commandline-1.4.19-standalone.zip to .jenkins/plugins/allure_plugin/

**Comment by monkpit** [comment]
I do not understand how to fix this message. Why does the plugin not install the ZIP by itself if the plugin is given the URL for allure-commandline.zip?

**Comment by monkpit** [comment]
If anyone else gets this error and does not know why - I had this error because in the allure plugin configuration inside of Jenkins (Jenkins > Manage Jenkins > Configure System > Allure Commandline > Allure Commandline Installations)  I had filled in the "label" field without reading the description of the field. The label field is not just a label - it means it will only apply to Jenkins agents that match what you type for the label. So if you clear out label and save the config, you will get rid of this error about ALLURE_HOME.

The point is, ALLURE_HOME is null because none of the agents are allowed to have Allure.

**Comment by jinxac** [comment]
@monkpit really helped.. thanks!!
