### ISSUE TITLE
[JENKINS-41556] Allure 2.11 plugin update is not compatible with Jenkins 2.32.1 version.

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/allure-plugin#492]
<p>My current jenkins version is : 2.32.1<br/>
Java version is : 1.8.0 Open JDK for the slave.</p>

<p>I had to apply some updates to Jenkins ant server. After that currently running UI Jobs started to fail because of report generation failure. It is a compatibility issue with an inbound Allure Jenkins plugin update.</p>

<p>Currently I run version 2.10 of the "Allure Jenkins Plugin". I installed update (2.11) which was available and installed but this turns out not to actually be compatible. The build is failing with following error :</p>

<p>ERROR: Build step failed with exception<br/>
java.lang.ClassCastException: [Lhudson.tools.ToolInstallation; cannot be cast to [Lru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation;<br/>
at<br/>
ru.yandex.qatools.allure.jenkins.AllureReportPublisherDescriptor.getCommandlineInstallations(AllureReportPublisherDescriptor.java:78)<br/>
at<br/>
ru.yandex.qatools.allure.jenkins.AllureReportPublisherDescriptor.getCommandlineInstallation(AllureReportPublisherDescriptor.java:83)<br/>
at<br/>
ru.yandex.qatools.allure.jenkins.AllureReportPublisher.getCommandline(AllureReportPublisher.java:188)<br/>
at<br/>
ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:160)<br/>
at<br/>
ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:90)<br/>
at<br/>
hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)<br/>
at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)<br/>
at<br/>
hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)<br/>
at<br/>
hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)<br/>
at hudson.model.Build$BuildExecution.post2(Build.java:185)<br/>
at<br/>
hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)<br/>
at hudson.model.Run.execute(Run.java:1745)<br/>
at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)<br/>
at hudson.model.ResourceController.execute(ResourceController.java:98)<br/>
at hudson.model.Executor.run(Executor.java:404)<br/>
Build step 'Allure Report' marked build as failure</p>

<p>When the plugin is reverted back to 2.10, all is fine.</p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=nachiket26">nachiket26</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-41556" target="_blank">Allure 2.11 plugin update is not compatible with Jenkins 2.32.1 version.</a></i></summary>
<i><ul>
<li><b>assignee</b>: <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/eroshenkoam.jpg" title="eroshenkoam's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=eroshenkoam">eroshenkoam</a>
<li><b>status</b>: Open
<li><b>priority</b>: Critical
<li><b>component(s)</b>: allure-plugin
<li><b>resolution</b>: Unresolved
<li><b>votes</b>: 2
<li><b>watchers</b>: 3
<li><b>imported</b>: 20260908-211411
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>My current jenkins version is : 2.32.1
Java version is : 1.8.0 Open JDK for the slave.</p>

<p>I had to apply some updates to Jenkins ant server. After that currently running UI Jobs started to fail because of report generation failure. It is a compatibility issue with an inbound Allure Jenkins plugin update.</p>

<p>Currently I run version 2.10 of the "Allure Jenkins Plugin". I installed update (2.11) which was available and installed but this turns out not to actually be compatible. The build is failing with following error :</p>

<p>ERROR: Build step failed with exception
java.lang.ClassCastException: [Lhudson.tools.ToolInstallation; cannot be cast to [Lru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation;
at
ru.yandex.qatools.allure.jenkins.AllureReportPublisherDescriptor.getCommandlineInstallations(AllureReportPublisherDescriptor.java:78)
at
ru.yandex.qatools.allure.jenkins.AllureReportPublisherDescriptor.getCommandlineInstallation(AllureReportPublisherDescriptor.java:83)
at
ru.yandex.qatools.allure.jenkins.AllureReportPublisher.getCommandline(AllureReportPublisher.java:188)
at
ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:160)
at
ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:90)
at
hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
at
hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
at
hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
at hudson.model.Build$BuildExecution.post2(Build.java:185)
at
hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
at hudson.model.Run.execute(Run.java:1745)
at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
at hudson.model.ResourceController.execute(ResourceController.java:98)
at hudson.model.Executor.run(Executor.java:404)
Build step 'Allure Report' marked build as failure</p>

<p>When the plugin is reverted back to 2.10, all is fine.</p></pre>
</details>
</details>
<details><summary><i>environment</i></summary>

```
Jenkins Version : 2.32.1<br/>
JDK : 1.8.0 Open JDK on Slave<br/>
OS : Ubuntu
```
</details>

**Comment by baev** [comment]
fixed via https://github.com/jenkinsci/allure-plugin/pull/79
