### ISSUE TITLE
Ran out of memory creating debug info for an error java.lang.OutOfMemoryError: GC overhead limit exceeded: error on Jenkins

### ISSUE THREAD

**Issue by dumbdev** [jenkinsci/allure-plugin#53]
Jenkins Version: 1.630
Allure Version: 1.4.23

Running TestSuite
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[AppClassLoader@7ea06d25] warning javax.* types are not being woven because the weaver option '-Xset:weaveJavaxPackages=true' has not been specified
Ran out of memory creating debug info for an error
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.HashMap.resize(HashMap.java:580)
	at java.util.HashMap.addEntry(HashMap.java:879)
	at java.util.HashMap.put(HashMap.java:505)
	at java.util.HashSet.add(HashSet.java:217)
	at org.aspectj.apache.bcel.generic.InstructionHandle.addTargeter(InstructionHandle.java:161)
	at org.aspectj.apache.bcel.generic.MethodGen.<init>(MethodGen.java:300)
	at org.aspectj.weaver.bcel.LazyMethodGen.initialize(LazyMethodGen.java:366)
	at org.aspectj.weaver.bcel.LazyMethodGen.markAsChanged(LazyMethodGen.java:534)
	at org.aspectj.weaver.bcel.LazyMethodGen.getBody(LazyMethodGen.java:924)
	at org.aspectj.weaver.bcel.BcelShadow.makeShadowForMethod(BcelShadow.java:679)
	at org.aspectj.weaver.bcel.BcelShadow.makeMethodExecution(BcelShadow.java:675)
	at org.aspectj.weaver.bcel.BcelShadow.makeMethodExecution(BcelShadow.java:655)
	at org.aspectj.weaver.bcel.BcelClassWeaver.match(BcelClassWeaver.java:2664)
	at org.aspectj.weaver.bcel.BcelClassWeaver.weave(BcelClassWeaver.java:480)
	at org.aspectj.weaver.bcel.BcelClassWeaver.weave(BcelClassWeaver.java:100)
	at org.aspectj.weaver.bcel.BcelWeaver.weave(BcelWeaver.java:1689)
	at org.aspectj.weaver.bcel.BcelWeaver.weaveWithoutDump(BcelWeaver.java:1633)
	at org.aspectj.weaver.bcel.BcelWeaver.weaveAndNotify(BcelWeaver.java:1398)
	at org.aspectj.weaver.bcel.BcelWeaver.weave(BcelWeaver.java:1184)
	at org.aspectj.weaver.tools.WeavingAdaptor.getWovenBytes(WeavingAdaptor.java:527)
	at org.aspectj.weaver.tools.WeavingAdaptor.weaveClass(WeavingAdaptor.java:363)
	at org.aspectj.weaver.loadtime.Aj.preProcess(Aj.java:121)
	at org.aspectj.weaver.loadtime.ClassPreProcessorAgentAdapter.transform(ClassPreProcessorAgentAdapter.java:54)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
[AppClassLoader@7ea06d25] abort trouble in: 
org.codehaus.groovy.runtime.ArrayUtil -- (OutOfMemoryError) GC overhead limit exceeded
GC overhead limit exceeded

**Comment by vania-pooh** [comment]
What is your heap size? How many test cases are you processing?

**Comment by dumbdev** [comment]
2GB, 236 test cases.

I have reduced it to only 1 test case, but outcome is the same. Thanks

**Comment by vania-pooh** [comment]
Summon eroshenkoam@, baev@.

**Comment by baev** [comment]
@dumbdev hi, sorry for the delay

Seems like your app have a huge classpath. So all you need is create [aop.xml](https://eclipse.org/aspectj/doc/next/devguide/ltw-configuration.html) and configure aspectJ to process only your project classes. An example if all your tests and steps located under `my.company.app` package create `META-INF/aop.xml` file with the following content:

```xml
<aspectj>
    <weaver>
        <exclude within="my.company.app..*"/>
    </weaver>
</aspectj>
```

**Comment by lanwen** [comment]
remark: in `${project.basedir}/resources/META-INF/aop.xml`

and seems that @baev mean `include` instead of `exclude`

**Comment by baev** [comment]
> and seems that @baev mean include instead of exclude

fixed

> remark: in ${project.basedir}/resources/META-INF/aop.xml

AspectJ looking for `META-INF/aop.xml` in your project classpath. In Maven project all files in `${project.basedir}/resources/` will be added to classpath, so basicly you're right.

**Comment by dumbdev** [comment]
Thanks Baev. Sorry for the late response was on holiday. 
All things are working now, reports generated nicely. Much appreciated. 

I will now close this issue.

**Comment by ksuzu** [comment]
I have the same problem. But when i add path to my test package in aop.xml , allure-results not generate.

**Comment by baev** [comment]
@ksuzu `aop.xml` should not affect allure-results (if you add it wrong only steps and attachments gonna be missed, but allure-results will still exists)

**Comment by ksuzu** [comment]
@baev I used https://github.com/d10xa/gradle-allure-plugin without writening AllureTestRunner. "allure-results" was generated automaticaly, but it worked only without configuration weaver-include.
In result I added AllureTestRunner by example https://github.com/allure-examples/allure-gradle-junit-example. It work with configuration weaver-include.

**Comment by iljapavlovs** [comment]
@baev I have added aop.xml and it solved OutOfMemoryError issue. However, I am not getting screenshots anymore and this is quite crucial for me. Do you have any ideas how to solve it?

**Comment by baev** [comment]
make sure you have include section for `io.qameta.allure` package

**Comment by vbaidak** [comment]
What I have in my **aop.xml**
```xml
<?xml version="1.0" encoding="utf-8"?>
<aspectj>
    <weaver>
        <include within="io.qameta..*" />
        <include within="org.junit..*" />
    </weaver>
</aspectj>
```
Note, that you don't need to add your project packages if you don't have aspects there.
You need only to add **io.qameta..*** (**ru.d10xa..*** for old version) for allure and **org.junit..*** for Junit

**Comment by iljapavlovs** [comment]
@vbaidak what about allure1? I have TestNg and allure 1 and tried with following **aop.xml**, but still no screenshots are added : 
```
<aspectj>
    <weaver>
        <include within="ru.yandex.qatools.allure..*" />
        <include within="org.testng..*" />
    </weaver>
</aspectj>

```

**Comment by vbaidak** [comment]
@iljapavlovs , you're right. You also need to add your application packages as well. I've edited my previous answer

**Comment by hemanth-dunzo** [comment]
issue fixed. Thank you.

**Comment by rgaduput** [comment]
Hi,
Facing same issue, is it possible to increase the heap size when generate allure reports ? Is there any such property available for allure?
