### ISSUE TITLE
Not able to generate report in jenkins(aborted due to exception java.lang.NoClassDefFoundError: ru/yandex/qatools/allure/jenkins/callables/CreateEnvironment)

### ISSUE THREAD

**Issue by emailtomit** [jenkinsci/allure-plugin#65]
Jenkins Version : 1.570
Allure Jenkin Plugin :- 2.10
Allure commandline :- 1.4.23.HOTFIX1

Able to see below error after run(FYI.. it is creating a allure report folder under workspace)

Unpacking https://oss.sonatype.org/content/repositories/releases/ru/yandex/qatools/allure/allure-commandline/1.4.23.HOTFIX1/allure-commandline-1.4.23.HOTFIX1-standalone.zip to /jobvolume/mit/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/1.4.23 on mesos-jenkins-8b168285fbe04e99bb939575be6b500f-mesos
ERROR: Publisher ru.yandex.qatools.allure.jenkins.AllureReportPublisher aborted due to exception
java.lang.NoClassDefFoundError: ru/yandex/qatools/allure/jenkins/callables/CreateEnvironment
    at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:169)
    at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:93)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:772)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:736)
    at hudson.model.Build$BuildExecution.post2(Build.java:183)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:685)
    at hudson.model.Run.execute(Run.java:1757)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:88)
    at hudson.model.Executor.run(Executor.java:234)
Recording test results
Finished: FAILURE

**Comment by eroshenkoam** [comment]
fixed #70
