### ISSUE TITLE
java.lang.ClassCastException: [Lhudson.tools.ToolInstallation; 

### ISSUE THREAD

**Issue by AlexanderPoleschuk** [jenkinsci/allure-plugin#75]
Jenkins: 2.43
Allure Core: 2.0 BETA3
Allure Jenkins plugin: 2.11
java 1.8.0_121
![citrix full desktop - desktop viewer 2017-01-31 23 14 02](https://cloud.githubusercontent.com/assets/9446141/22483233/6b381f6e-e80d-11e6-9dab-4565c96f6841.png)

Re-adding of allure in Global Tool Configuration in Jenkins have fixed the issue.

ERROR: Build step failed with exception
java.lang.ClassCastException: [Lhudson.tools.ToolInstallation; cannot be cast to [Lru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation;
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisherDescriptor.getCommandlineInstallations(AllureReportPublisherDescriptor.java:78)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisherDescriptor.getCommandlineInstallation(AllureReportPublisherDescriptor.java:83)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.getCommandline(AllureReportPublisher.java:188)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:160)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:90)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1067)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1753)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:544)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)
Build step 'Allure Report' marked build as failure
Finished: FAILURE

**Comment by baev** [comment]
As workaround you can reinstall allure commandline (remove it from tools configuration and then add again)
