### ISSUE TITLE
unable to generate allure report on Jenkins with specified fields in Environment tab.

### ISSUE THREAD

**Issue by dheeraj7771** [jenkinsci/allure-plugin#85]
## Issue
the coping of "environment.properties" file to allue-result breaks the zip file and report generator can't open the zip file(i tried to give rwx permissions to all users but no success). hence unable to show report and environment details.
my environment.properties looks like
```
Environment = Dev
Browser = chrome
URL = https://dev.someurl.com/
```
### Context
- **Jenkins version**: 2.46
- **Job type**: Freestyle.

- **Allure plugin version**: 2.13
- **Allure commandline version**: 1.5.2

### Problem description
i am using "nightwatch-allure-adapter" and trying to add some fields("current run env", "browser name", "URL") to environment tab of allure report dynamically on Jenkins.

I was able to do that locally by adding environment.properties file and coping it to allure result dir just before generating the report.
by adding script command like below in my package.json.

```
"scripts": {
      "clean": "rm -rf allure-results",
      "pretest": "npm run clean",
      "test": "multi='progress=- nightwatch-allure-reporter=-' nightwatch",
      "prereport": "cp environment.properties allure-results/",
      "report": "allure generate allure-results -o allure-report && allure report open -o allure-report"
  },
```
<img width="1431" alt="screen shot 2017-02-24 at 10 32 54 am" src="https://cloud.githubusercontent.com/assets/16159307/23319814/fec9237c-fa8c-11e6-824a-5c5b86dd9187.png">
However i have two issues still pending.

1. this approach is static, i am not sure how i can update my environment.properties dynamically with env and browser details.

2. on Jenkins the coping of this file to allue-result breaks the zip file and report generator can't open the zip file(i tried to give rwx permissions to all users). hence unable to show report and environment details.

<img width="630" alt="screen shot 2017-02-24 at 12 27 48 pm" src="https://cloud.githubusercontent.com/assets/16159307/23319758/c2e8c97a-fa8c-11e6-9cc8-19bd8f647df9.png">

### Logs & Traces
<img width="1117" alt="screen shot 2017-02-24 at 12 21 09 pm" src="https://cloud.githubusercontent.com/assets/16159307/23319772/ce28d0b4-fa8c-11e6-988d-a866c73e9883.png">

`A problem occurred while processing the request. Please check our bug tracker to see if a similar problem has already been reported. If it is already reported, please vote and put a comment on it to let us gauge the impact of the problem. If you think this is a new issue, please file a new issue. When you file an issue, make sure to add the entire stack trace, along with the version of Jenkins and relevant plugins. The users list might be also useful in understanding what has happened.

Stack trace

java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:120)
	at ru.yandex.qatools.allure.jenkins.AllureReportBuildAction$ArchiveReportBrowser.generateResponse(AllureReportBuildAction.java:85)
	at org.kohsuke.stapler.HttpResponseRenderer$Default.handleHttpResponse(HttpResponseRenderer.java:124)
	at org.kohsuke.stapler.HttpResponseRenderer$Default.generateResponse(HttpResponseRenderer.java:69)
	at org.kohsuke.stapler.Function.renderResponse(Function.java:136)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:119)
	at org.kohsuke.stapler.MetaClass$11.dispatch(MetaClass.java:397)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:845)
	at org.kohsuke.stapler.MetaClass$10.dispatch(MetaClass.java:374)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:845)
	at org.kohsuke.stapler.MetaClass$10.dispatch(MetaClass.java:374)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:845)
	at org.kohsuke.stapler.MetaClass$5.doDispatch(MetaClass.java:248)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:845)
	at org.kohsuke.stapler.MetaClass$5.doDispatch(MetaClass.java:248)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:845)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:135)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:126)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:553)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by dheeraj7771** [comment]
just to support above issue, i tried to generate and host the allure report(after moving environment.properties file to allure-results dir) using "publish HTML report" Jenkins plug in.
and it worked.

**Comment by emailtomit** [comment]
@dheeraj7771 .. I am not able to generate report using HTML .. can you please take a look below config??

<img width="961" alt="screen shot 2017-03-13 at 6 42 21 pm" src="https://cloud.githubusercontent.com/assets/9697955/23879736/102fcdda-081d-11e7-9d25-43e39fac190a.png">

Error :- 
ERROR: Step ‘Allure Report’ aborted due to exception: 
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:120)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.makeCopyForEveryPath(AllureReportPublisher.java:236)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.copyHistory(AllureReportPublisher.java:231)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.prepareResults(AllureReportPublisher.java:197)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:85)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1753)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at PROJECT level /workspace/Functional-Test/allure-report to /var/lib/jenkins/jobs/Functional-Test/htmlreports/HTML_Report
ERROR: Specified HTML directory '/workspace/Functional-Test/allure-report' does not exist.
Recording test results

**Comment by dheeraj7771** [comment]
@emailtomit the allure report zip issue you are getting is an actual bug https://github.com/jenkinsci/allure-plugin/issues/73
allure plugin itself hosts the report so you don't need to combine the two.
the zip issue is intermittent and if/when the correct zip is created you will be able to view the report without HTML hosting.

To make it work without allure plugin, i had a workaround.
steps to generate allure report on Jenkins and host on HTML report.

1. I added shell command(can add a script as well) to build steps, which will generate the allure report at specified path 
<img width="591" alt="screen shot 2017-03-15 at 8 50 37 am" src="https://cloud.githubusercontent.com/assets/16159307/23957754/6324cc16-095d-11e7-9d44-e2e2d32b815d.png">

2. create a zip file and archive it.
3. create an HTML hosting by specifying the path of allure-report which is generated in step 1.
<img width="1114" alt="screen shot 2017-03-15 at 8 52 54 am" src="https://cloud.githubusercontent.com/assets/16159307/23957936/dc25dae2-095d-11e7-8756-602b9367f066.png">

PS:- make sure that the allure command line installer version is correct and already installed on the machine you are using to run the test.
in this approach you are not using any allure plugin but a command line tool and html plugin.

**Comment by eroshenkoam** [comment]
fixes in 2.17

**Comment by kavmaria** [comment]
Hi Team,

We are using  gradle with Spock and Geb (groovy) for UI automation . I could like to integrate allure report in jenkins , so I have installed allure-plugin & configured 

Job configuration : 

Post build Action  
------------------
 1) selected allure report 
2)  Path {WORKSPACE}/PROJECTNAME/build/allure-report 

Allure Commends 
Name : report 
installed automatically yes 
from Maven central  2.2.1

3) build as gradle wrapper 

use gradle wrapper yes selected
tasks as test 

[test] $ C:\Users\test\.jenkins\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\Report\bin\allure.bat generate -o C:\Users\test\.jenkins\workspace\test\allure-report
allure-results does not exists
Report successfully generated to C:\Users\test\.jenkins\workspace\test\allure-report

Question 1 

Report generated in Jenkins but  Tc execution result is not updated ,it showing only default allure report 

Question 2 
How to configure adopter for allure report with combination gradle & spock  , Share steps or document 



Regards,
M.Kaver

**Comment by eroshenkoam** [comment]
@kavmaria can you make new issue for your request?

**Comment by joby-h20** [comment]
@eroshenkoam  I am still unable to generate the reports even with the latest allure jenkins plugin.  Could you please let me know if the fix was through any workaround or any jenkins env settings?
