### ISSUE TITLE
Allure plugin doesn't work with pipeline plugin 

### ISSUE THREAD

**Issue by egordqa** [jenkinsci/allure-plugin#88]
### Context
- Jenkins version: org.jenkins-ci.main:jenkins-war:2.32.3
- Job type: Pipeline

- **Allure plugin version**:  2.13
- **Allure commandline version**:  1.5.2

Problem description:
I have installed Allure Cli from Maven on 
/var/lib/jenkins/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/Maven_Allure/
 I've added pipeline step for allure report generation (from snippet generation): 
allure([commandline: 'Maven_Allure', includeProperties: false, jdk: '', properties: [], reportBuildPolicy: 'ALWAYS', results: [[path: 'allure-results']]])
But build failed with exception:

`java.io.IOException: Can't find allure commandline <null>
	at ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation$1.call(AllureCommandlineInstallation.java:46)
	at ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation$1.call(AllureCommandlineInstallation.java:41)
	at hudson.remoting.LocalChannel.call(LocalChannel.java:45)
	at ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation.getExecutable(AllureCommandlineInstallation.java:41)
	at ru.yandex.qatools.allure.jenkins.ReportBuilder.getVersion(ReportBuilder.java:83)
	at ru.yandex.qatools.allure.jenkins.ReportBuilder.build(ReportBuilder.java:42)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:162)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:86)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:69)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:59)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:221)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

If a add Allure step for post build action for freestyle projects - it works correctly.
Also when I add bash script for allure report generation
`sh '''
   /var/lib/jenkins/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/Maven_Allure/bin/allure generate allure-results -o allure-report
    '''`
 and publish it with publishHTML plugin it also works.

**Comment by drweber** [comment]
Got the same issue with same configurations of Jenkins and also jenkins-war:2.32.1 too.

**Comment by yurchenkosv** [comment]
Got same issue too

**Comment by egordqa** [comment]
Thanks! It works!

**Comment by drweber** [comment]
confirmed

**Comment by shureek** [comment]
It doesn't work for me. I've tried this step in Jenkins file:
```
stage('Publish results') {
            steps {
                allure config: [
                    commandline: 'Maven_Allure',
                    includeProperties: false,
                    jdk: '',
                    properties: [],
                    reportBuildPolicy: 'ALWAYS',
                    results: [[path: 'out/allure']]
                ]
            }
        }
```
and got this error:
```
[trade_pipeline] $ C:\Docker\Jenkins\slave-1\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\allure\bin\allure.bat generate -o "C:\Docker\Jenkins\slave-1\workspace\trade_pipeline\allure-report"
Invalid ALLURE_HOME: /C:\Docker\Jenkins\slave-1\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\allure is not a valid allure commandline directory 
```
then I added this to allure.bat to remove leading slash:
```
if "%ALLURE_HOME:~0,1%" == "/" (
    echo Changing ALLURE_HOME from %ALLURE_HOME% to %ALLURE_HOME:~1%
    set "ALLURE_HOME=%ALLURE_HOME:~1%"
)
```
And it almost worked, but wrote:
```
[trade_pipeline] $ C:\Docker\Jenkins\slave-1\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\allure\bin\allure.bat generate -o "C:\Docker\Jenkins\slave-1\workspace\trade_pipeline\allure-report"
Changing ALLURE_HOME from /C:\Docker\Jenkins\slave-1\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\allure to C:\Docker\Jenkins\slave-1\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\allure
{}
io.airlift.airline.ParseArgumentsMissingException: Required parameters are missing: Results directories
	at io.airlift.airline.Cli.validate(Cli.java:144)
	at io.airlift.airline.Cli.parse(Cli.java:116)
	at io.airlift.airline.Cli.parse(Cli.java:97)
	at ru.yandex.qatools.allure.CommandLine.main(CommandLine.java:44)
Allure report was successfully generated.
```
That build was successful, but allure report archive was empty.
How can I specify input and output paths?
