### ISSUE TITLE
Report generate fail when the result path is a dir link

### ISSUE THREAD

**Issue by wuhuizuo** [jenkinsci/allure-plugin#95]
### Context
- **Jenkins version**: 2.46.1
- **Job type**: Freestyle

- **Allure plugin version**: 2.14
- **Allure commandline version**: 1.5.2

### Problem description

‘Allure Report’ aborted due to exception: java.nio.file.FileAlreadyExistsException when the target path is a dir link
- allure xml data is in `{WORKSPACE}rspec_reports`, rspec_reports is link to another dir.
- allure report set `result path`: rspec_reports
- Allure Report step failed!

### Logs & Traces

```bash
root@Jenkins-CI-agents-25:~/workspace/PipeTest# pwd
/home/jenkins/workspace/PipeTest
root@Jenkins-CI-agents-25:~/workspace/PipeTest# ls -ld rspec_reports
lrwxrwxrwx 1 root root 44 Apr  6 11:10 rspec_reports -> /var/jenkins_home/PipeTe
st/185/rspec_reports
root@Jenkins-CI-agents-25:~/workspace/PipeTest#
```

jenkins log:
```
Build step 'Trigger/call builds on other projects' marked build as failure
ERROR: Step ‘Allure Report’ aborted due to exception: 
java.nio.file.FileAlreadyExistsException: /home/jenkins/workspace/PipeTest/rspec_reports
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:727)
	at ru.yandex.qatools.allure.jenkins.callables.AbstractAddInfo.invoke(AbstractAddInfo.java:24)
	at ru.yandex.qatools.allure.jenkins.callables.AbstractAddInfo.invoke(AbstractAddInfo.java:19)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2731)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:336)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at hudson.remoting.Engine$1$1.run(Engine.java:94)
	at java.lang.Thread.run(Thread.java:745)
	at ......remote call to JNLP4-connect connection from 10.42.179.44/10.42.179.44:51463(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1545)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:253)
	at hudson.remoting.Channel.call(Channel.java:830)
	at hudson.FilePath.act(FilePath.java:985)
Caused: java.io.IOException: remote file operation failed: /home/jenkins/workspace/PipeTest/rspec_reports at hudson.remoting.Channel@67f26f8f:JNLP4-connect connection from 10.42.179.44/10.42.179.44:51463
	at hudson.FilePath.act(FilePath.java:992)
	at hudson.FilePath.act(FilePath.java:974)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.addTestRunInfo(AllureReportPublisher.java:226)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.prepareResults(AllureReportPublisher.java:217)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:84)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1753)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)
Finished: FAILURE
```

**Comment by wuhuizuo** [comment]
v2.10 is OK!
